import { DraftGoalkeeper } from "../types";


export const draftGoalkeepers: Array<DraftGoalkeeper> = [
   {
      "id": "001",
      "name": "Marc Arus",
      "role": "PORTERO",
      "age": 19,
      "foot": "Diestro",
      "height": 186,
      "weight": 75,
      "reflex": 62,
      "block": 70,
      "kick": 60,
      "stretch": 73,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/001.jpg"
   },
   {
      "id": "002",
      "name": "Pol Lechuga",
      "role": "PORTERO",
      "age": 26,
      "foot": "Diestro",
      "height": 171,
      "weight": 70,
      "reflex": 81,
      "block": 84,
      "kick": 70,
      "stretch": 60,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/002.jpg"
   },
   {
      "id": "015",
      "name": "Xavier Sánchez",
      "role": "PORTERO",
      "age": 25,
      "foot": "Diestro",
      "height": 184,
      "weight": 93,
      "reflex": 55,
      "block": 60,
      "kick": 53,
      "stretch": 56,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/015.jpg"
   },
   {
      "id": "030",
      "name": "Iván Fajardo",
      "role": "PORTERO",
      "age": 25,
      "foot": "Diestro",
      "height": 194,
      "weight": 98,
      "reflex": 61,
      "block": 60,
      "kick": 74,
      "stretch": 63,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/030.jpg"
   },
   {
      "id": "045",
      "name": "Josep Corderas",
      "role": "PORTERO",
      "age": 29,
      "foot": "Diestro",
      "height": 184,
      "weight": 79,
      "reflex": 60,
      "block": 74,
      "kick": 60,
      "stretch": 60,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/045.jpg"
   },
   {
      "id": "059",
      "name": "Sergi Aguilar",
      "role": "PORTERO",
      "age": 27,
      "foot": "Diestro",
      "height": 184,
      "weight": 82,
      "reflex": 70,
      "block": 73,
      "kick": 81,
      "stretch": 71,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/059.jpg"
   },
   {
      "id": "060",
      "name": "Marc Briones",
      "role": "PORTERO",
      "age": 24,
      "foot": "Diestro",
      "height": 184,
      "weight": 74,
      "reflex": 82,
      "block": 81,
      "kick": 80,
      "stretch": 84,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/060.jpg"
   },
   {
      "id": "073",
      "name": "Enric Planas",
      "role": "PORTERO",
      "age": 21,
      "foot": "Diestro",
      "height": 191,
      "weight": 84,
      "reflex": 71,
      "block": 70,
      "kick": 66,
      "stretch": 68,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/073.jpg"
   },
   {
      "id": "074",
      "name": "Raul Perez",
      "role": "PORTERO",
      "age": 19,
      "foot": "Diestro",
      "height": 189,
      "weight": 76,
      "reflex": 80,
      "block": 71,
      "kick": 72,
      "stretch": 66,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/074.jpg"
   },
   {
      "id": "089",
      "name": "Javier Morales",
      "role": "PORTERO",
      "age": 20,
      "foot": "Diestro",
      "height": 185,
      "weight": 86,
      "reflex": 83,
      "block": 83,
      "kick": 76,
      "stretch": 74,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/089.jpg"
   },
   {
      "id": "090",
      "name": "Jorge Ibáñez",
      "role": "PORTERO",
      "age": 19,
      "foot": "Diestro",
      "height": 183,
      "weight": 79,
      "reflex": 84,
      "block": 83,
      "kick": 82,
      "stretch": 78,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/090.jpg"
   },
   {
      "id": "104",
      "name": "Mario León",
      "role": "PORTERO",
      "age": 39,
      "foot": "Diestro",
      "height": 182,
      "weight": 88,
      "reflex": 71,
      "block": 73,
      "kick": 62,
      "stretch": 80,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/104.jpg"
   },
   {
      "id": "110",
      "name": "Daniel Pérez",
      "role": "PORTERO",
      "age": 24,
      "foot": "Diestro",
      "height": 180,
      "weight": 72,
      "reflex": 90,
      "block": 83,
      "kick": 84,
      "stretch": 86,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/110.jpg"
   },
   {
      "id": "117",
      "name": "Sergio Ródenas",
      "role": "PORTERO",
      "age": 21,
      "foot": "Diestro",
      "height": 180,
      "weight": 70,
      "reflex": 81,
      "block": 84,
      "kick": 74,
      "stretch": 76,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/117.jpg"
   },
   {
      "id": "118",
      "name": "Jose Manuel Segovia",
      "role": "PORTERO",
      "age": 31,
      "foot": "Diestro",
      "height": 183,
      "weight": 84,
      "reflex": 85,
      "block": 92,
      "kick": 86,
      "stretch": 86,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/118.jpg"
   },
   {
      "id": "133",
      "name": "Adria Gutiérrez",
      "role": "PORTERO",
      "age": 18,
      "foot": "Diestro",
      "height": 185,
      "weight": 78,
      "reflex": 82,
      "block": 74,
      "kick": 75,
      "stretch": 84,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/133.jpg"
   },
   {
      "id": "134",
      "name": "Victor Cócera",
      "role": "PORTERO",
      "age": 29,
      "foot": "Diestro",
      "height": 175,
      "weight": 71,
      "reflex": 83,
      "block": 92,
      "kick": 86,
      "stretch": 87,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/134.jpg"
   },
   {
      "id": "161",
      "name": "Ricardo Lopez",
      "role": "PORTERO",
      "age": 51,
      "foot": "Zurdo",
      "height": 187,
      "weight": 95,
      "reflex": 82,
      "block": 91,
      "kick": 86,
      "stretch": 92,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/161.jpg"
   },
   {
      "id": "162",
      "name": "Ignacio Berché",
      "role": "PORTERO",
      "age": 23,
      "foot": "Diestro",
      "height": 178,
      "weight": 70,
      "reflex": 72,
      "block": 77,
      "kick": 79,
      "stretch": 80,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/162.jpg"
   },
   {
      "id": "179",
      "name": "Jaume Llaveria",
      "role": "PORTERO",
      "age": 37,
      "foot": "Diestro",
      "height": 173,
      "weight": 68,
      "reflex": 71,
      "block": 73,
      "kick": 66,
      "stretch": 63,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/179.jpg"
   },
   {
      "id": "194",
      "name": "Iu Morral",
      "role": "PORTERO",
      "age": 22,
      "foot": "Zurdo",
      "height": 174,
      "weight": 65,
      "reflex": 71,
      "block": 84,
      "kick": 79,
      "stretch": 83,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/194.jpg"
   },
   {
      "id": "195",
      "name": "Alex Garcia",
      "role": "PORTERO",
      "age": 20,
      "foot": "Diestro",
      "height": 183,
      "weight": 73,
      "reflex": 86,
      "block": 70,
      "kick": 76,
      "stretch": 71,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/195.jpg"
   },
   {
      "id": "208",
      "name": "Pol Zapata",
      "role": "PORTERO",
      "age": 23,
      "foot": "Zurdo",
      "height": 180,
      "weight": 70,
      "reflex": 86,
      "block": 87,
      "kick": 84,
      "stretch": 94,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/208.jpg"
   },
   {
      "id": "209",
      "name": "Joan Canet",
      "role": "PORTERO",
      "age": 19,
      "foot": "Diestro",
      "height": 185,
      "weight": 83,
      "reflex": 84,
      "block": 95,
      "kick": 84,
      "stretch": 85,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/209.jpg"
   }
]
