import { DraftPlayer } from "../types"

export const draftPlayers: Array<DraftPlayer> = [
   {
      "id": "003",
      "name": "Xavier Garcia",
      "role": "DEFENSA",
      "age": 24,
      "foot": "Diestro",
      "height": 174,
      "weight": 69,
      "physical": 69,
      "speed": 74,
      "shoot": 70,
      "skill": 66,
      "pass": 83,
      "defense": 71,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/003.jpg"
   },
   {
      "id": "004",
      "name": "Iker López",
      "role": "DEFENSA",
      "age": 19,
      "foot": "Diestro",
      "height": 180,
      "weight": 68,
      "physical": 67,
      "speed": 73,
      "shoot": 79,
      "skill": 69,
      "pass": 84,
      "defense": 71,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/004.jpg"
   },
   {
      "id": "005",
      "name": "Joel Bañuls",
      "role": "DEFENSA",
      "age": 21,
      "foot": "Zurdo",
      "height": 173,
      "weight": 65,
      "physical": 58,
      "speed": 71,
      "shoot": 81,
      "skill": 76,
      "pass": 76,
      "defense": 80,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/005.jpg"
   },
   {
      "id": "006",
      "name": "Flavio Ruggeri",
      "role": "DEFENSA",
      "age": 22,
      "foot": "Diestro",
      "height": 174,
      "weight": 68,
      "physical": 56,
      "speed": 70,
      "shoot": 68,
      "skill": 81,
      "pass": 68,
      "defense": 85,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/006.jpg"
   },
   {
      "id": "007",
      "name": "Iñaki Villalba",
      "role": "MEDIO",
      "age": 22,
      "foot": "Diestro",
      "height": 180,
      "weight": 80,
      "physical": 64,
      "speed": 73,
      "shoot": 79,
      "skill": 70,
      "pass": 75,
      "defense": 70,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/007.jpg"
   },
   {
      "id": "008",
      "name": "David Cabezas",
      "role": "MEDIO",
      "age": 22,
      "foot": "Diestro",
      "height": 181,
      "weight": 77,
      "physical": 72,
      "speed": 72,
      "shoot": 67,
      "skill": 73,
      "pass": 69,
      "defense": 69,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/008.jpg"
   },
   {
      "id": "009",
      "name": "Toti Sàlvia",
      "role": "MEDIO",
      "age": 21,
      "foot": "Diestro",
      "height": 171,
      "weight": 63,
      "physical": 58,
      "speed": 72,
      "shoot": 80,
      "skill": 78,
      "pass": 69,
      "defense": 73,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/009.jpg"
   },
   {
      "id": "011",
      "name": "Edgar Alvaro",
      "role": "DELANTERO",
      "age": 22,
      "foot": "Diestro",
      "height": 181,
      "weight": 75,
      "physical": 82,
      "speed": 73,
      "shoot": 81,
      "skill": 85,
      "pass": 55,
      "defense": 70,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/011.jpg"
   },
   {
      "id": "012",
      "name": "Steven Rodríguez",
      "role": "DELANTERO",
      "age": 20,
      "foot": "Zurdo",
      "height": 182,
      "weight": 70,
      "physical": 49,
      "speed": 72,
      "shoot": 72,
      "skill": 75,
      "pass": 53,
      "defense": 79,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/012.jpg"
   },
   {
      "id": "013",
      "name": "Pau Mañé",
      "role": "DELANTERO",
      "age": 25,
      "foot": "Diestro",
      "height": 173,
      "weight": 73,
      "physical": 69,
      "speed": 83,
      "shoot": 82,
      "skill": 80,
      "pass": 77,
      "defense": 69,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/013.jpg"
   },
   {
      "id": "018",
      "name": "Roman Alegre",
      "role": "DEFENSA",
      "age": 20,
      "foot": "Zurdo",
      "height": 184,
      "weight": 81,
      "physical": 71,
      "speed": 73,
      "shoot": 68,
      "skill": 86,
      "pass": 76,
      "defense": 66,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/018.jpg"
   },
   {
      "id": "020",
      "name": "Jadir Cirera",
      "role": "DEFENSA",
      "age": 26,
      "foot": "Diestro",
      "height": 187,
      "weight": 90,
      "physical": 55,
      "speed": 72,
      "shoot": 67,
      "skill": 58,
      "pass": 57,
      "defense": 68,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/020.jpg"
   },
   {
      "id": "021",
      "name": "Álvaro García",
      "role": "MEDIO",
      "age": 26,
      "foot": "Diestro",
      "height": 182,
      "weight": 75,
      "physical": 69,
      "speed": 72,
      "shoot": 79,
      "skill": 77,
      "pass": 78,
      "defense": 65,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/021.jpg"
   },
   {
      "id": "023",
      "name": "Raúl Lao",
      "role": "MEDIO",
      "age": 20,
      "foot": "Zurdo",
      "height": 178,
      "weight": 78,
      "physical": 69,
      "speed": 73,
      "shoot": 89,
      "skill": 74,
      "pass": 65,
      "defense": 77,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/023.jpg"
   },
   {
      "id": "024",
      "name": "Joan Inés",
      "role": "MEDIO",
      "age": 25,
      "foot": "Diestro",
      "height": 186,
      "weight": 73,
      "physical": 60,
      "speed": 72,
      "shoot": 78,
      "skill": 64,
      "pass": 64,
      "defense": 63,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/024.jpg"
   },
   {
      "id": "025",
      "name": "Joan Poch",
      "role": "DELANTERO",
      "age": 21,
      "foot": "Zurdo",
      "height": 189,
      "weight": 76,
      "physical": 53,
      "speed": 68,
      "shoot": 84,
      "skill": 79,
      "pass": 79,
      "defense": 73,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/025.jpg"
   },
   {
      "id": "026",
      "name": "Marc Granero",
      "role": "DELANTERO",
      "age": 21,
      "foot": "Zurdo",
      "height": 183,
      "weight": 77,
      "physical": 62,
      "speed": 72,
      "shoot": 70,
      "skill": 56,
      "pass": 65,
      "defense": 72,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/026.jpg"
   },
   {
      "id": "027",
      "name": "Victor Sotelo",
      "role": "DELANTERO",
      "age": 20,
      "foot": "Diestro",
      "height": 161,
      "weight": 57,
      "physical": 51,
      "speed": 72,
      "shoot": 76,
      "skill": 54,
      "pass": 79,
      "defense": 59,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/027.jpg"
   },
   {
      "id": "028",
      "name": "Kilian Honorato",
      "role": "DELANTERO",
      "age": 23,
      "foot": "Diestro",
      "height": 182,
      "weight": 77,
      "physical": 70,
      "speed": 72,
      "shoot": 87,
      "skill": 78,
      "pass": 69,
      "defense": 73,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/028.jpg"
   },
   {
      "id": "031",
      "name": "Ian González",
      "role": "DEFENSA",
      "age": 19,
      "foot": "Diestro",
      "height": 186,
      "weight": 82,
      "physical": 54,
      "speed": 87,
      "shoot": 64,
      "skill": 74,
      "pass": 54,
      "defense": 76,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/031.jpg"
   },
   {
      "id": "032",
      "name": "Arnau Martínez",
      "role": "DEFENSA",
      "age": 23,
      "foot": "Diestro",
      "height": 185,
      "weight": 88,
      "physical": 62,
      "speed": 74,
      "shoot": 81,
      "skill": 68,
      "pass": 60,
      "defense": 82,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/032.jpg"
   },
   {
      "id": "034",
      "name": "David López",
      "role": "DEFENSA",
      "age": 34,
      "foot": "Zurdo",
      "height": 177,
      "weight": 78,
      "physical": 48,
      "speed": 70,
      "shoot": 80,
      "skill": 81,
      "pass": 62,
      "defense": 75,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/034.jpg"
   },
   {
      "id": "037",
      "name": "Lucca Ribeiro",
      "role": "MEDIO",
      "age": 20,
      "foot": "Zurdo",
      "height": 170,
      "weight": 65,
      "physical": 77,
      "speed": 72,
      "shoot": 77,
      "skill": 77,
      "pass": 50,
      "defense": 83,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/037.jpg"
   },
   {
      "id": "038",
      "name": "Bernat Juarez",
      "role": "MEDIO",
      "age": 26,
      "foot": "Diestro",
      "height": 180,
      "weight": 68,
      "physical": 65,
      "speed": 71,
      "shoot": 75,
      "skill": 71,
      "pass": 55,
      "defense": 77,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/038.jpg"
   },
   {
      "id": "039",
      "name": "Mark Sorroche",
      "role": "DELANTERO",
      "age": 18,
      "foot": "Diestro",
      "height": 180,
      "weight": 66,
      "physical": 74,
      "speed": 93,
      "shoot": 87,
      "skill": 78,
      "pass": 58,
      "defense": 73,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/039.jpg"
   },
   {
      "id": "040",
      "name": "Marino Gómez",
      "role": "DELANTERO",
      "age": 25,
      "foot": "Diestro",
      "height": 173,
      "weight": 67,
      "physical": 59,
      "speed": 73,
      "shoot": 81,
      "skill": 68,
      "pass": 83,
      "defense": 69,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/040.jpg"
   },
   {
      "id": "041",
      "name": "Joan Mariné",
      "role": "DELANTERO",
      "age": 26,
      "foot": "Diestro",
      "height": 177,
      "weight": 69,
      "physical": 50,
      "speed": 71,
      "shoot": 72,
      "skill": 73,
      "pass": 55,
      "defense": 77,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/041.jpg"
   },
   {
      "id": "042",
      "name": "Roger de la Villa",
      "role": "DELANTERO",
      "age": 26,
      "foot": "Diestro",
      "height": 174,
      "weight": 68,
      "physical": 61,
      "speed": 73,
      "shoot": 81,
      "skill": 78,
      "pass": 68,
      "defense": 69,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/042.jpg"
   },
   {
      "id": "043",
      "name": "Sergio del Pino",
      "role": "MEDIO",
      "age": 34,
      "foot": "Diestro",
      "height": 177,
      "weight": 100,
      "physical": 44,
      "speed": 72,
      "shoot": 65,
      "skill": 72,
      "pass": 66,
      "defense": 70,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/043.jpg"
   },
   {
      "id": "044",
      "name": "Daniel Pérez",
      "role": "MEDIO",
      "age": 25,
      "foot": "Diestro",
      "height": 174,
      "weight": 75,
      "physical": 75,
      "speed": 96,
      "shoot": 78,
      "skill": 66,
      "pass": 88,
      "defense": 62,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/044.jpg"
   },
   {
      "id": "047",
      "name": "Daniel Santiago",
      "role": "DEFENSA",
      "age": 21,
      "foot": "Diestro",
      "height": 188,
      "weight": 87,
      "physical": 69,
      "speed": 64,
      "shoot": 79,
      "skill": 75,
      "pass": 55,
      "defense": 83,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/047.jpg"
   },
   {
      "id": "048",
      "name": "Alex Campuzano",
      "role": "DEFENSA",
      "age": 22,
      "foot": "Diestro",
      "height": 179,
      "weight": 73,
      "physical": 53,
      "speed": 70,
      "shoot": 80,
      "skill": 78,
      "pass": 78,
      "defense": 83,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/048.jpg"
   },
   {
      "id": "049",
      "name": "Miquel Fernández",
      "role": "DEFENSA",
      "age": 19,
      "foot": "Diestro",
      "height": 179,
      "weight": 77,
      "physical": 53,
      "speed": 70,
      "shoot": 86,
      "skill": 55,
      "pass": 58,
      "defense": 69,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/049.jpg"
   },
   {
      "id": "051",
      "name": "Cristian Ubón",
      "role": "MEDIO",
      "age": 21,
      "foot": "Diestro",
      "height": 176,
      "weight": 76,
      "physical": 52,
      "speed": 69,
      "shoot": 78,
      "skill": 81,
      "pass": 73,
      "defense": 85,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/051.jpg"
   },
   {
      "id": "052",
      "name": "Franc Cortés",
      "role": "MEDIO",
      "age": 21,
      "foot": "Diestro",
      "height": 181,
      "weight": 73,
      "physical": 46,
      "speed": 64,
      "shoot": 77,
      "skill": 81,
      "pass": 87,
      "defense": 74,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/052.jpg"
   },
   {
      "id": "053",
      "name": "Marcel Miquel",
      "role": "MEDIO",
      "age": 26,
      "foot": "Zurdo",
      "height": 183,
      "weight": 71,
      "physical": 47,
      "speed": 64,
      "shoot": 76,
      "skill": 71,
      "pass": 56,
      "defense": 74,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/053.jpg"
   },
   {
      "id": "054",
      "name": "Teimurazi Korkotashvili",
      "role": "MEDIO",
      "age": 28,
      "foot": "Diestro",
      "height": 168,
      "weight": 58,
      "physical": 45,
      "speed": 72,
      "shoot": 75,
      "skill": 73,
      "pass": 74,
      "defense": 70,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/054.jpg"
   },
   {
      "id": "055",
      "name": "Javier Vila",
      "role": "DELANTERO",
      "age": 27,
      "foot": "Diestro",
      "height": 182,
      "weight": 69,
      "physical": 53,
      "speed": 64,
      "shoot": 65,
      "skill": 79,
      "pass": 76,
      "defense": 73,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/055.jpg"
   },
   {
      "id": "056",
      "name": "Victor Hidalgo",
      "role": "DELANTERO",
      "age": 24,
      "foot": "Diestro",
      "height": 184,
      "weight": 86,
      "physical": 56,
      "speed": 72,
      "shoot": 71,
      "skill": 68,
      "pass": 65,
      "defense": 74,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/056.jpg"
   },
   {
      "id": "057",
      "name": "Benito Martínez",
      "role": "DELANTERO",
      "age": 24,
      "foot": "Diestro",
      "height": 180,
      "weight": 76,
      "physical": 49,
      "speed": 70,
      "shoot": 69,
      "skill": 70,
      "pass": 52,
      "defense": 77,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/057.jpg"
   },
   {
      "id": "061",
      "name": "Marcos Guerrero",
      "role": "DEFENSA",
      "age": 20,
      "foot": "Diestro",
      "height": 175,
      "weight": 73,
      "physical": 55,
      "speed": 71,
      "shoot": 82,
      "skill": 83,
      "pass": 77,
      "defense": 83,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/061.jpg"
   },
   {
      "id": "062",
      "name": "Nacho Jordà",
      "role": "DEFENSA",
      "age": 23,
      "foot": "Zurdo",
      "height": 177,
      "weight": 77,
      "physical": 51,
      "speed": 72,
      "shoot": 70,
      "skill": 64,
      "pass": 79,
      "defense": 64,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/062.jpg"
   },
   {
      "id": "063",
      "name": "Mario Reyes",
      "role": "DEFENSA",
      "age": 31,
      "foot": "Zurdo",
      "height": 172,
      "weight": 72,
      "physical": 53,
      "speed": 66,
      "shoot": 76,
      "skill": 73,
      "pass": 72,
      "defense": 69,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/063.jpg"
   },
   {
      "id": "064",
      "name": "David Soriano",
      "role": "DEFENSA",
      "age": 22,
      "foot": "Diestro",
      "height": 186,
      "weight": 80,
      "physical": 70,
      "speed": 71,
      "shoot": 80,
      "skill": 56,
      "pass": 78,
      "defense": 57,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/064.jpg"
   },
   {
      "id": "065",
      "name": "Paulin Ntonga",
      "role": "MEDIO",
      "age": 35,
      "foot": "Diestro",
      "height": 177,
      "weight": 85,
      "physical": 50,
      "speed": 71,
      "shoot": 63,
      "skill": 60,
      "pass": 50,
      "defense": 66,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/065.jpg"
   },
   {
      "id": "066",
      "name": "Marc Galvany",
      "role": "MEDIO",
      "age": 18,
      "foot": "Diestro",
      "height": 188,
      "weight": 72,
      "physical": 63,
      "speed": 73,
      "shoot": 86,
      "skill": 81,
      "pass": 87,
      "defense": 90,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/066.jpg"
   },
   {
      "id": "067",
      "name": "Gilles Vidal",
      "role": "MEDIO",
      "age": 20,
      "foot": "Diestro",
      "height": 176,
      "weight": 73,
      "physical": 58,
      "speed": 82,
      "shoot": 65,
      "skill": 81,
      "pass": 81,
      "defense": 73,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/067.jpg"
   },
   {
      "id": "068",
      "name": "Joel Pascual",
      "role": "MEDIO",
      "age": 21,
      "foot": "Diestro",
      "height": 177,
      "weight": 73,
      "physical": 58,
      "speed": 72,
      "shoot": 80,
      "skill": 66,
      "pass": 69,
      "defense": 71,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/068.jpg"
   },
   {
      "id": "069",
      "name": "Benjamín Sierra",
      "role": "DELANTERO",
      "age": 26,
      "foot": "Diestro",
      "height": 177,
      "weight": 76,
      "physical": 66,
      "speed": 73,
      "shoot": 66,
      "skill": 77,
      "pass": 77,
      "defense": 75,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/069.jpg"
   },
   {
      "id": "070",
      "name": "Raul Martinez",
      "role": "DELANTERO",
      "age": 20,
      "foot": "Zurdo",
      "height": 172,
      "weight": 68,
      "physical": 50,
      "speed": 73,
      "shoot": 70,
      "skill": 84,
      "pass": 76,
      "defense": 73,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/070.jpg"
   },
   {
      "id": "071",
      "name": "Jose Luis Blanco",
      "role": "DELANTERO",
      "age": 22,
      "foot": "Diestro",
      "height": 164,
      "weight": 65,
      "physical": 54,
      "speed": 73,
      "shoot": 65,
      "skill": 71,
      "pass": 66,
      "defense": 65,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/071.jpg"
   },
   {
      "id": "072",
      "name": "Adrià de Castro",
      "role": "DELANTERO",
      "age": 24,
      "foot": "Zurdo",
      "height": 173,
      "weight": 65,
      "physical": 45,
      "speed": 70,
      "shoot": 80,
      "skill": 82,
      "pass": 89,
      "defense": 81,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/072.jpg"
   },
   {
      "id": "075",
      "name": "Adrià Santiago",
      "role": "DEFENSA",
      "age": 21,
      "foot": "Diestro",
      "height": 183,
      "weight": 72,
      "physical": 46,
      "speed": 67,
      "shoot": 71,
      "skill": 78,
      "pass": 74,
      "defense": 70,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/075.jpg"
   },
   {
      "id": "076",
      "name": "Gabriel Cichero",
      "role": "DEFENSA",
      "age": 38,
      "foot": "Zurdo",
      "height": 185,
      "weight": 80,
      "physical": 49,
      "speed": 73,
      "shoot": 66,
      "skill": 76,
      "pass": 75,
      "defense": 74,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/076.jpg"
   },
   {
      "id": "078",
      "name": "Victor Torres",
      "role": "DEFENSA",
      "age": 19,
      "foot": "Zurdo",
      "height": 190,
      "weight": 85,
      "physical": 39,
      "speed": 71,
      "shoot": 74,
      "skill": 69,
      "pass": 73,
      "defense": 60,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/078.jpg"
   },
   {
      "id": "079",
      "name": "Aleix Ripol",
      "role": "MEDIO",
      "age": 23,
      "foot": "Zurdo",
      "height": 170,
      "weight": 68,
      "physical": 53,
      "speed": 72,
      "shoot": 76,
      "skill": 71,
      "pass": 75,
      "defense": 69,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/079.jpg"
   },
   {
      "id": "082",
      "name": "Jorge Valverde",
      "role": "MEDIO",
      "age": 29,
      "foot": "Diestro",
      "height": 175,
      "weight": 74,
      "physical": 54,
      "speed": 63,
      "shoot": 64,
      "skill": 63,
      "pass": 62,
      "defense": 68,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/082.jpg"
   },
   {
      "id": "083",
      "name": "Frank Martínez",
      "role": "DELANTERO",
      "age": 27,
      "foot": "Diestro",
      "height": 184,
      "weight": 86,
      "physical": 50,
      "speed": 72,
      "shoot": 74,
      "skill": 76,
      "pass": 78,
      "defense": 68,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/083.jpg"
   },
   {
      "id": "085",
      "name": "Alejandro Garcia",
      "role": "DEFENSA",
      "age": 23,
      "foot": "Diestro",
      "height": 170,
      "weight": 70,
      "physical": 51,
      "speed": 72,
      "shoot": 57,
      "skill": 68,
      "pass": 70,
      "defense": 74,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/085.jpg"
   },
   {
      "id": "086",
      "name": "Axel Lesan",
      "role": "DELANTERO",
      "age": 24,
      "foot": "Diestro",
      "height": 167,
      "weight": 62,
      "physical": 56,
      "speed": 72,
      "shoot": 71,
      "skill": 71,
      "pass": 68,
      "defense": 73,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/086.jpg"
   },
   {
      "id": "087",
      "name": "Iván López",
      "role": "MEDIO",
      "age": 26,
      "foot": "Zurdo",
      "height": 183,
      "weight": 78,
      "physical": 47,
      "speed": 67,
      "shoot": 79,
      "skill": 80,
      "pass": 75,
      "defense": 71,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/087.jpg"
   },
   {
      "id": "088",
      "name": "Ramon Mirabet",
      "role": "MEDIO",
      "age": 38,
      "foot": "Diestro",
      "height": 179,
      "weight": 74,
      "physical": 41,
      "speed": 67,
      "shoot": 75,
      "skill": 76,
      "pass": 81,
      "defense": 60,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/088.jpg"
   },
   {
      "id": "091",
      "name": "Àlex Gutiérrez",
      "role": "DEFENSA",
      "age": 28,
      "foot": "Zurdo",
      "height": 180,
      "weight": 80,
      "physical": 62,
      "speed": 73,
      "shoot": 76,
      "skill": 74,
      "pass": 58,
      "defense": 77,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/091.jpg"
   },
   {
      "id": "092",
      "name": "Aleix Massegú",
      "role": "DEFENSA",
      "age": 27,
      "foot": "Diestro",
      "height": 181,
      "weight": 76,
      "physical": 76,
      "speed": 71,
      "shoot": 78,
      "skill": 74,
      "pass": 83,
      "defense": 79,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/092.jpg"
   },
   {
      "id": "093",
      "name": "Raúl Ledo",
      "role": "DEFENSA",
      "age": 21,
      "foot": "Zurdo",
      "height": 165,
      "weight": 65,
      "physical": 51,
      "speed": 67,
      "shoot": 70,
      "skill": 81,
      "pass": 72,
      "defense": 70,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/093.jpg"
   },
   {
      "id": "094",
      "name": "Edu Ranchal",
      "role": "DELANTERO",
      "age": 29,
      "foot": "Diestro",
      "height": 173,
      "weight": 70,
      "physical": 63,
      "speed": 72,
      "shoot": 63,
      "skill": 74,
      "pass": 72,
      "defense": 74,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/094.jpg"
   },
   {
      "id": "095",
      "name": "Ramon Roca",
      "role": "MEDIO",
      "age": 37,
      "foot": "Zurdo",
      "height": 174,
      "weight": 70,
      "physical": 47,
      "speed": 70,
      "shoot": 53,
      "skill": 74,
      "pass": 74,
      "defense": 72,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/095.jpg"
   },
   {
      "id": "096",
      "name": "Iván Martín",
      "role": "MEDIO",
      "age": 30,
      "foot": "Diestro",
      "height": 180,
      "weight": 79,
      "physical": 60,
      "speed": 73,
      "shoot": 78,
      "skill": 70,
      "pass": 58,
      "defense": 68,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/096.jpg"
   },
   {
      "id": "098",
      "name": "Noel López",
      "role": "MEDIO",
      "age": 22,
      "foot": "Zurdo",
      "height": 168,
      "weight": 73,
      "physical": 68,
      "speed": 73,
      "shoot": 79,
      "skill": 89,
      "pass": 70,
      "defense": 67,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/098.jpg"
   },
   {
      "id": "099",
      "name": "Adrian Biboum",
      "role": "DELANTERO",
      "age": 23,
      "foot": "Diestro",
      "height": 185,
      "weight": 84,
      "physical": 58,
      "speed": 72,
      "shoot": 80,
      "skill": 68,
      "pass": 88,
      "defense": 70,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/099.jpg"
   },
   {
      "id": "101",
      "name": "Ferran Gimenez",
      "role": "DELANTERO",
      "age": 30,
      "foot": "Diestro",
      "height": 172,
      "weight": 75,
      "physical": 55,
      "speed": 72,
      "shoot": 81,
      "skill": 68,
      "pass": 63,
      "defense": 55,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/101.jpg"
   },
   {
      "id": "106",
      "name": "Andrew Turner",
      "role": "DEFENSA",
      "age": 18,
      "foot": "Diestro",
      "height": 174,
      "weight": 58,
      "physical": 59,
      "speed": 73,
      "shoot": 72,
      "skill": 80,
      "pass": 77,
      "defense": 80,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/106.jpg"
   },
   {
      "id": "108",
      "name": "Sergi Sauras",
      "role": "DEFENSA",
      "age": 30,
      "foot": "Diestro",
      "height": 189,
      "weight": 77,
      "physical": 69,
      "speed": 73,
      "shoot": 69,
      "skill": 65,
      "pass": 62,
      "defense": 82,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/108.jpg"
   },
   {
      "id": "109",
      "name": "Álvaro Hinojosa",
      "role": "MEDIO",
      "age": 22,
      "foot": "Diestro",
      "height": 176,
      "weight": 73,
      "physical": 70,
      "speed": 73,
      "shoot": 81,
      "skill": 65,
      "pass": 60,
      "defense": 64,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/109.jpg"
   },
   {
      "id": "111",
      "name": "Iván Nuevo",
      "role": "MEDIO",
      "age": 22,
      "foot": "Diestro",
      "height": 165,
      "weight": 63,
      "physical": 63,
      "speed": 70,
      "shoot": 80,
      "skill": 83,
      "pass": 61,
      "defense": 73,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/111.jpg"
   },
   {
      "id": "112",
      "name": "Feliu Torrus",
      "role": "MEDIO",
      "age": 28,
      "foot": "Diestro",
      "height": 165,
      "weight": 66,
      "physical": 64,
      "speed": 72,
      "shoot": 83,
      "skill": 82,
      "pass": 60,
      "defense": 84,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/112.jpg"
   },
   {
      "id": "114",
      "name": "Pablo Beguer",
      "role": "DELANTERO",
      "age": 27,
      "foot": "Zurdo",
      "height": 172,
      "weight": 67,
      "physical": 57,
      "speed": 73,
      "shoot": 84,
      "skill": 86,
      "pass": 66,
      "defense": 71,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/114.jpg"
   },
   {
      "id": "115",
      "name": "Giovanni Ferinu",
      "role": "DELANTERO",
      "age": 24,
      "foot": "Diestro",
      "height": 183,
      "weight": 81,
      "physical": 67,
      "speed": 71,
      "shoot": 74,
      "skill": 85,
      "pass": 75,
      "defense": 77,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/115.jpg"
   },
   {
      "id": "119",
      "name": "Bruno Gumà",
      "role": "DEFENSA",
      "age": 22,
      "foot": "Zurdo",
      "height": 178,
      "weight": 78,
      "physical": 51,
      "speed": 66,
      "shoot": 77,
      "skill": 78,
      "pass": 76,
      "defense": 84,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/119.jpg"
   },
   {
      "id": "120",
      "name": "Pau Ruiz",
      "role": "DEFENSA",
      "age": 24,
      "foot": "Diestro",
      "height": 178,
      "weight": 66,
      "physical": 56,
      "speed": 72,
      "shoot": 76,
      "skill": 74,
      "pass": 68,
      "defense": 76,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/120.jpg"
   },
   {
      "id": "121",
      "name": "Carlos Val",
      "role": "DEFENSA",
      "age": 22,
      "foot": "Diestro",
      "height": 183,
      "weight": 77,
      "physical": 64,
      "speed": 73,
      "shoot": 77,
      "skill": 81,
      "pass": 71,
      "defense": 85,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/121.jpg"
   },
   {
      "id": "123",
      "name": "Marc Pluvins",
      "role": "MEDIO",
      "age": 23,
      "foot": "Diestro",
      "height": 177,
      "weight": 70,
      "physical": 58,
      "speed": 72,
      "shoot": 78,
      "skill": 87,
      "pass": 70,
      "defense": 71,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/123.jpg"
   },
   {
      "id": "124",
      "name": "Roger Carbó",
      "role": "MEDIO",
      "age": 24,
      "foot": "Zurdo",
      "height": 173,
      "weight": 81,
      "physical": 49,
      "speed": 71,
      "shoot": 63,
      "skill": 66,
      "pass": 67,
      "defense": 62,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/124.jpg"
   },
   {
      "id": "125",
      "name": "Pol Montserrat",
      "role": "MEDIO",
      "age": 30,
      "foot": "Diestro",
      "height": 181,
      "weight": 77,
      "physical": 56,
      "speed": 71,
      "shoot": 83,
      "skill": 73,
      "pass": 63,
      "defense": 69,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/125.jpg"
   },
   {
      "id": "126",
      "name": "Marc Amigó",
      "role": "MEDIO",
      "age": 27,
      "foot": "Diestro",
      "height": 179,
      "weight": 72,
      "physical": 48,
      "speed": 67,
      "shoot": 69,
      "skill": 64,
      "pass": 68,
      "defense": 54,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/126.jpg"
   },
   {
      "id": "127",
      "name": "Raul Dorado",
      "role": "DELANTERO",
      "age": 22,
      "foot": "Diestro",
      "height": 194,
      "weight": 93,
      "physical": 52,
      "speed": 72,
      "shoot": 80,
      "skill": 78,
      "pass": 71,
      "defense": 58,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/127.jpg"
   },
   {
      "id": "128",
      "name": "Dorkis Perez",
      "role": "DELANTERO",
      "age": 20,
      "foot": "Diestro",
      "height": 180,
      "weight": 74,
      "physical": 54,
      "speed": 72,
      "shoot": 78,
      "skill": 71,
      "pass": 54,
      "defense": 72,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/128.jpg"
   },
   {
      "id": "129",
      "name": "Ismael Cabello",
      "role": "DELANTERO",
      "age": 33,
      "foot": "Diestro",
      "height": 180,
      "weight": 75,
      "physical": 54,
      "speed": 77,
      "shoot": 80,
      "skill": 58,
      "pass": 57,
      "defense": 56,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/129.jpg"
   },
   {
      "id": "130",
      "name": "Marc Palanca",
      "role": "DELANTERO",
      "age": 26,
      "foot": "Diestro",
      "height": 174,
      "weight": 73,
      "physical": 55,
      "speed": 73,
      "shoot": 65,
      "skill": 59,
      "pass": 59,
      "defense": 57,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/130.jpg"
   },
   {
      "id": "131",
      "name": "Victor Molina",
      "role": "DELANTERO",
      "age": 25,
      "foot": "Zurdo",
      "height": 173,
      "weight": 69,
      "physical": 56,
      "speed": 73,
      "shoot": 74,
      "skill": 72,
      "pass": 82,
      "defense": 71,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/131.jpg"
   },
   {
      "id": "132",
      "name": "Llorenç Genesca",
      "role": "DELANTERO",
      "age": 24,
      "foot": "Diestro",
      "height": 187,
      "weight": 80,
      "physical": 53,
      "speed": 71,
      "shoot": 75,
      "skill": 66,
      "pass": 59,
      "defense": 67,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/132.jpg"
   },
   {
      "id": "137",
      "name": "Cristian Valle",
      "role": "MEDIO",
      "age": 32,
      "foot": "Zurdo",
      "height": 179,
      "weight": 74,
      "physical": 52,
      "speed": 71,
      "shoot": 76,
      "skill": 78,
      "pass": 86,
      "defense": 66,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/137.jpg"
   },
   {
      "id": "140",
      "name": "Joel Macarulla",
      "role": "MEDIO",
      "age": 22,
      "foot": "Zurdo",
      "height": 191,
      "weight": 82,
      "physical": 77,
      "speed": 72,
      "shoot": 72,
      "skill": 87,
      "pass": 72,
      "defense": 75,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/140.jpg"
   },
   {
      "id": "141",
      "name": "Jonathan A. Jiménez",
      "role": "MEDIO",
      "age": 32,
      "foot": "Diestro",
      "height": 178,
      "weight": 77,
      "physical": 73,
      "speed": 85,
      "shoot": 80,
      "skill": 62,
      "pass": 60,
      "defense": 62,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/141.jpg"
   },
   {
      "id": "142",
      "name": "Pau Grabolosa",
      "role": "MEDIO",
      "age": 18,
      "foot": "Zurdo",
      "height": 182,
      "weight": 67,
      "physical": 77,
      "speed": 72,
      "shoot": 64,
      "skill": 72,
      "pass": 75,
      "defense": 64,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/142.jpg"
   },
   {
      "id": "143",
      "name": "Alejandro Ramírez",
      "role": "DELANTERO",
      "age": 22,
      "foot": "Diestro",
      "height": 180,
      "weight": 73,
      "physical": 56,
      "speed": 69,
      "shoot": 73,
      "skill": 81,
      "pass": 57,
      "defense": 87,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/143.jpg"
   },
   {
      "id": "145",
      "name": "Iago Rodrigues",
      "role": "DELANTERO",
      "age": 24,
      "foot": "Diestro",
      "height": 170,
      "weight": 65,
      "physical": 52,
      "speed": 69,
      "shoot": 66,
      "skill": 68,
      "pass": 63,
      "defense": 85,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/145.jpg"
   },
   {
      "id": "150",
      "name": "David Torregrosa",
      "role": "MEDIO",
      "age": 27,
      "foot": "Diestro",
      "height": 171,
      "weight": 66,
      "physical": 54,
      "speed": 89,
      "shoot": 61,
      "skill": 61,
      "pass": 58,
      "defense": 69,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/150.jpg"
   },
   {
      "id": "151",
      "name": "Lluis Alsina",
      "role": "MEDIO",
      "age": 21,
      "foot": "Diestro",
      "height": 174,
      "weight": 65,
      "physical": 74,
      "speed": 93,
      "shoot": 87,
      "skill": 84,
      "pass": 76,
      "defense": 73,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/151.jpg"
   },
   {
      "id": "152",
      "name": "Javier Capilla",
      "role": "MEDIO",
      "age": 35,
      "foot": "Zurdo",
      "height": 171,
      "weight": 70,
      "physical": 40,
      "speed": 73,
      "shoot": 78,
      "skill": 77,
      "pass": 70,
      "defense": 78,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/152.jpg"
   },
   {
      "id": "153",
      "name": "Carlos García",
      "role": "DELANTERO",
      "age": 23,
      "foot": "Diestro",
      "height": 170,
      "weight": 72,
      "physical": 47,
      "speed": 71,
      "shoot": 69,
      "skill": 82,
      "pass": 72,
      "defense": 68,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/153.jpg"
   },
   {
      "id": "154",
      "name": "Raúl Morillo",
      "role": "DELANTERO",
      "age": 22,
      "foot": "Zurdo",
      "height": 167,
      "weight": 66,
      "physical": 58,
      "speed": 79,
      "shoot": 70,
      "skill": 57,
      "pass": 97,
      "defense": 59,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/154.jpg"
   },
   {
      "id": "156",
      "name": "Ivan Pérez",
      "role": "DELANTERO",
      "age": 20,
      "foot": "Diestro",
      "height": 178,
      "weight": 73,
      "physical": 64,
      "speed": 77,
      "shoot": 63,
      "skill": 62,
      "pass": 52,
      "defense": 63,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/156.jpg"
   },
   {
      "id": "157",
      "name": "Manel Torras",
      "role": "MEDIO",
      "age": 21,
      "foot": "Zurdo",
      "height": 178,
      "weight": 70,
      "physical": 41,
      "speed": 65,
      "shoot": 74,
      "skill": 75,
      "pass": 69,
      "defense": 78,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/157.jpg"
   },
   {
      "id": "159",
      "name": "Antonio Segura",
      "role": "MEDIO",
      "age": 28,
      "foot": "Diestro",
      "height": 173,
      "weight": 66,
      "physical": 52,
      "speed": 70,
      "shoot": 70,
      "skill": 54,
      "pass": 72,
      "defense": 54,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/159.jpg"
   },
   {
      "id": "160",
      "name": "Pau Fernández",
      "role": "MEDIO",
      "age": 21,
      "foot": "Diestro",
      "height": 182,
      "weight": 63,
      "physical": 62,
      "speed": 71,
      "shoot": 71,
      "skill": 75,
      "pass": 82,
      "defense": 82,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/160.jpg"
   },
   {
      "id": "164",
      "name": "Sergio Sánchez",
      "role": "MEDIO",
      "age": 29,
      "foot": "Diestro",
      "height": 180,
      "weight": 69,
      "physical": 43,
      "speed": 65,
      "shoot": 75,
      "skill": 82,
      "pass": 79,
      "defense": 84,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/164.jpg"
   },
   {
      "id": "165",
      "name": "Cristhian E. Aguilera",
      "role": "MEDIO",
      "age": 26,
      "foot": "Diestro",
      "height": 170,
      "weight": 70,
      "physical": 69,
      "speed": 74,
      "shoot": 68,
      "skill": 62,
      "pass": 65,
      "defense": 72,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/165.jpg"
   },
   {
      "id": "166",
      "name": "Gerardo Barral",
      "role": "MEDIO",
      "age": 20,
      "foot": "Diestro",
      "height": 175,
      "weight": 68,
      "physical": 47,
      "speed": 63,
      "shoot": 69,
      "skill": 70,
      "pass": 77,
      "defense": 69,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/166.jpg"
   },
   {
      "id": "168",
      "name": "Lluc Riera",
      "role": "DELANTERO",
      "age": 27,
      "foot": "Diestro",
      "height": 186,
      "weight": 79,
      "physical": 57,
      "speed": 69,
      "shoot": 61,
      "skill": 78,
      "pass": 67,
      "defense": 77,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/168.jpg"
   },
   {
      "id": "169",
      "name": "Alvaro Pons",
      "role": "DEFENSA",
      "age": 22,
      "foot": "Diestro",
      "height": 181,
      "weight": 69,
      "physical": 41,
      "speed": 55,
      "shoot": 61,
      "skill": 76,
      "pass": 68,
      "defense": 68,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/169.jpg"
   },
   {
      "id": "170",
      "name": "Juan Quero",
      "role": "MEDIO",
      "age": 38,
      "foot": "Diestro",
      "height": 160,
      "weight": 58,
      "physical": 67,
      "speed": 83,
      "shoot": 73,
      "skill": 83,
      "pass": 86,
      "defense": 74,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/170.jpg"
   },
   {
      "id": "171",
      "name": "David Alba",
      "role": "DELANTERO",
      "age": 36,
      "foot": "Diestro",
      "height": 169,
      "weight": 60,
      "physical": 75,
      "speed": 75,
      "shoot": 80,
      "skill": 73,
      "pass": 65,
      "defense": 64,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/171.jpg"
   },
   {
      "id": "172",
      "name": "Manu Valenzuela",
      "role": "DELANTERO",
      "age": 29,
      "foot": "Zurdo",
      "height": 179,
      "weight": 98,
      "physical": 73,
      "speed": 71,
      "shoot": 85,
      "skill": 60,
      "pass": 92,
      "defense": 62,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/172.jpg"
   },
   {
      "id": "173",
      "name": "Noel Bayarri",
      "role": "DEFENSA",
      "age": 34,
      "foot": "Diestro",
      "height": 182,
      "weight": 82,
      "physical": 62,
      "speed": 72,
      "shoot": 71,
      "skill": 72,
      "pass": 64,
      "defense": 68,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/173.jpg"
   },
   {
      "id": "174",
      "name": "Jonathan Mengeli",
      "role": "DEFENSA",
      "age": 33,
      "foot": "Diestro",
      "height": 186,
      "weight": 85,
      "physical": 82,
      "speed": 86,
      "shoot": 74,
      "skill": 76,
      "pass": 66,
      "defense": 77,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/174.jpg"
   },
   {
      "id": "175",
      "name": "Jordi Ros",
      "role": "MEDIO",
      "age": 26,
      "foot": "Diestro",
      "height": 177,
      "weight": 73,
      "physical": 78,
      "speed": 72,
      "shoot": 86,
      "skill": 83,
      "pass": 75,
      "defense": 80,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/175.jpg"
   },
   {
      "id": "176",
      "name": "Andres Serrano",
      "role": "DEFENSA",
      "age": 18,
      "foot": "Diestro",
      "height": 193,
      "weight": 82,
      "physical": 69,
      "speed": 74,
      "shoot": 69,
      "skill": 63,
      "pass": 71,
      "defense": 77,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/176.jpg"
   },
   {
      "id": "177",
      "name": "Goran Ehsan",
      "role": "MEDIO",
      "age": 24,
      "foot": "Zurdo",
      "height": 171,
      "weight": 63,
      "physical": 61,
      "speed": 92,
      "shoot": 72,
      "skill": 71,
      "pass": 51,
      "defense": 60,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/177.jpg"
   },
   {
      "id": "181",
      "name": "Victor Baranera",
      "role": "MEDIO",
      "age": 21,
      "foot": "Diestro",
      "height": 175,
      "weight": 72,
      "physical": 60,
      "speed": 73,
      "shoot": 62,
      "skill": 74,
      "pass": 69,
      "defense": 68,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/181.jpg"
   },
   {
      "id": "182",
      "name": "Francesc Purtí",
      "role": "MEDIO",
      "age": 23,
      "foot": "Zurdo",
      "height": 174,
      "weight": 71,
      "physical": 71,
      "speed": 73,
      "shoot": 74,
      "skill": 82,
      "pass": 66,
      "defense": 78,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/182.jpg"
   },
   {
      "id": "183",
      "name": "Marc Pelaz",
      "role": "MEDIO",
      "age": 19,
      "foot": "Diestro",
      "height": 181,
      "weight": 73,
      "physical": 59,
      "speed": 71,
      "shoot": 76,
      "skill": 86,
      "pass": 78,
      "defense": 72,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/183.jpg"
   },
   {
      "id": "184",
      "name": "Oscar Rivero",
      "role": "MEDIO",
      "age": 22,
      "foot": "Diestro",
      "height": 181,
      "weight": 70,
      "physical": 64,
      "speed": 73,
      "shoot": 82,
      "skill": 87,
      "pass": 60,
      "defense": 75,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/184.jpg"
   },
   {
      "id": "188",
      "name": "Guillem Ruiz",
      "role": "DELANTERO",
      "age": 24,
      "foot": "Diestro",
      "height": 178,
      "weight": 66,
      "physical": 52,
      "speed": 69,
      "shoot": 84,
      "skill": 81,
      "pass": 63,
      "defense": 80,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/188.jpg"
   },
   {
      "id": "189",
      "name": "Carlos Torrentbó",
      "role": "DELANTERO",
      "age": 31,
      "foot": "Diestro",
      "height": 173,
      "weight": 70,
      "physical": 59,
      "speed": 73,
      "shoot": 73,
      "skill": 75,
      "pass": 76,
      "defense": 72,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/189.jpg"
   },
   {
      "id": "190",
      "name": "Juan Rivas",
      "role": "DELANTERO",
      "age": 34,
      "foot": "Diestro",
      "height": 175,
      "weight": 73,
      "physical": 66,
      "speed": 75,
      "shoot": 63,
      "skill": 69,
      "pass": 70,
      "defense": 70,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/190.jpg"
   },
   {
      "id": "192",
      "name": "Lautaro Nicolas",
      "role": "DELANTERO",
      "age": 26,
      "foot": "Diestro",
      "height": 181,
      "weight": 76,
      "physical": 59,
      "speed": 79,
      "shoot": 75,
      "skill": 69,
      "pass": 70,
      "defense": 70,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/192.jpg"
   },
   {
      "id": "193",
      "name": "Ciprian Bezdiga",
      "role": "DELANTERO",
      "age": 25,
      "foot": "Zurdo",
      "height": 190,
      "weight": 85,
      "physical": 47,
      "speed": 72,
      "shoot": 57,
      "skill": 60,
      "pass": 65,
      "defense": 67,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/193.jpg"
   },
   {
      "id": "196",
      "name": "Carlos González",
      "role": "MEDIO",
      "age": 26,
      "foot": "Diestro",
      "height": 172,
      "weight": 72,
      "physical": 67,
      "speed": 80,
      "shoot": 64,
      "skill": 77,
      "pass": 82,
      "defense": 71,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/196.jpg"
   },
   {
      "id": "197",
      "name": "Xavier Molas",
      "role": "MEDIO",
      "age": 41,
      "foot": "Zurdo",
      "height": 171,
      "weight": 71,
      "physical": 72,
      "speed": 73,
      "shoot": 76,
      "skill": 81,
      "pass": 84,
      "defense": 78,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/197.jpg"
   },
   {
      "id": "198",
      "name": "Bernat Rovira",
      "role": "MEDIO",
      "age": 22,
      "foot": "Zurdo",
      "height": 180,
      "weight": 68,
      "physical": 64,
      "speed": 73,
      "shoot": 82,
      "skill": 79,
      "pass": 94,
      "defense": 64,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/198.jpg"
   },
   {
      "id": "199",
      "name": "Aleix Lage",
      "role": "MEDIO",
      "age": 31,
      "foot": "Diestro",
      "height": 180,
      "weight": 80,
      "physical": 64,
      "speed": 87,
      "shoot": 65,
      "skill": 74,
      "pass": 72,
      "defense": 70,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/199.jpg"
   },
   {
      "id": "204",
      "name": "Mauro Alguacil",
      "role": "DELANTERO",
      "age": 18,
      "foot": "Zurdo",
      "height": 182,
      "weight": 77,
      "physical": 65,
      "speed": 73,
      "shoot": 83,
      "skill": 68,
      "pass": 76,
      "defense": 59,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/204.jpg"
   },
   {
      "id": "205",
      "name": "Oriol Pons",
      "role": "DELANTERO",
      "age": 20,
      "foot": "Zurdo",
      "height": 177,
      "weight": 85,
      "physical": 78,
      "speed": 72,
      "shoot": 78,
      "skill": 65,
      "pass": 61,
      "defense": 65,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/205.jpg"
   },
   {
      "id": "207",
      "name": "Oriol Boada",
      "role": "DELANTERO",
      "age": 24,
      "foot": "Diestro",
      "height": 178,
      "weight": 80,
      "physical": 53,
      "speed": 72,
      "shoot": 80,
      "skill": 79,
      "pass": 63,
      "defense": 73,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/207.jpg"
   },
   {
      "id": "210",
      "name": "Arturo Bárcena",
      "role": "MEDIO",
      "age": 23,
      "foot": "Diestro",
      "height": 177,
      "weight": 77,
      "physical": 67,
      "speed": 76,
      "shoot": 81,
      "skill": 61,
      "pass": 50,
      "defense": 65,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/210.jpg"
   },
   {
      "id": "211",
      "name": "Aaron Ropero",
      "role": "MEDIO",
      "age": 21,
      "foot": "Diestro",
      "height": 169,
      "weight": 73,
      "physical": 57,
      "speed": 72,
      "shoot": 82,
      "skill": 72,
      "pass": 72,
      "defense": 68,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/211.jpg"
   },
   {
      "id": "213",
      "name": "Roger Bonet",
      "role": "MEDIO",
      "age": 35,
      "foot": "Diestro",
      "height": 168,
      "weight": 59,
      "physical": 75,
      "speed": 71,
      "shoot": 73,
      "skill": 85,
      "pass": 73,
      "defense": 68,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/213.jpg"
   },
   {
      "id": "214",
      "name": "Marc Juanico",
      "role": "MEDIO",
      "age": 24,
      "foot": "Diestro",
      "height": 172,
      "weight": 67,
      "physical": 61,
      "speed": 73,
      "shoot": 71,
      "skill": 77,
      "pass": 57,
      "defense": 72,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/214.jpg"
   },
   {
      "id": "215",
      "name": "Ruben G. Tremiño",
      "role": "DELANTERO",
      "age": 26,
      "foot": "Zurdo",
      "height": 185,
      "weight": 85,
      "physical": 76,
      "speed": 71,
      "shoot": 83,
      "skill": 78,
      "pass": 55,
      "defense": 71,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/215.jpg"
   },
   {
      "id": "216",
      "name": "Manel Torralba",
      "role": "DELANTERO",
      "age": 25,
      "foot": "Diestro",
      "height": 192,
      "weight": 85,
      "physical": 70,
      "speed": 72,
      "shoot": 77,
      "skill": 65,
      "pass": 81,
      "defense": 62,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/216.jpg"
   },
   {
      "id": "217",
      "name": "Jacobo Fernández",
      "role": "DELANTERO",
      "age": 26,
      "foot": "Diestro",
      "height": 185,
      "weight": 80,
      "physical": 68,
      "speed": 86,
      "shoot": 84,
      "skill": 84,
      "pass": 81,
      "defense": 67,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/217.jpg"
   },
   {
      "id": "220",
      "name": "Raúl de Regás",
      "role": "DELANTERO",
      "age": 23,
      "foot": "Diestro",
      "height": 187,
      "weight": 73,
      "physical": 66,
      "speed": 70,
      "shoot": 73,
      "skill": 65,
      "pass": 88,
      "defense": 69,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/220.jpg"
   },
   {
      "id": "221",
      "name": "Alex Sala",
      "role": "DELANTERO",
      "age": 23,
      "foot": "Diestro",
      "height": 182,
      "weight": 70,
      "physical": 61,
      "speed": 72,
      "shoot": 73,
      "skill": 66,
      "pass": 67,
      "defense": 71,
      "img": "https://kingsleague.pro/wp-content/uploads/2022/12/221.jpg"
   }
]
