import { GamesProps } from "../types";

export const games: Array<GamesProps> = [
   {
      week: 1,
      date: '01/01/2023',
      played: true,
      results: [
         {
            team_a: 'Rayo de Barcelona',
            team_a_red: 'RDB',
            logo_a: 'https://kingsleague.pro/wp-content/uploads/2022/11/rayo-barcelona.svg',
            team_b: '1K FC',
            team_b_red: '1K',
            logo_b: 'https://kingsleague.pro/wp-content/uploads/2022/11/1k.svg',
            goals_a: 2,
            goals_b: 4,
         },
         {
            team_a: 'Kunisports',
            team_a_red: 'KNS',
            logo_a: 'https://kingsleague.pro/wp-content/uploads/2022/11/kunisports.svg',
            team_b: 'Jijantes FC',
            team_b_red: 'JFC',
            logo_b: 'https://kingsleague.pro/wp-content/uploads/2022/11/jijantes-fc.svg',
            goals_a: 2,
            goals_b: 1,
         },
         {
            team_a: 'El Barrio',
            team_a_red: 'ELB',
            logo_a: 'https://kingsleague.pro/wp-content/uploads/2022/11/el-bbarrio.svg',
            team_b: 'PIO FC',
            team_b_red: 'PIO',
            logo_b: 'https://kingsleague.pro/wp-content/uploads/2022/11/pio.svg',
            goals_a: 5,
            goals_b: 0,
         },
         {
            team_a: 'Los Troncos FC',
            team_a_red: 'TFC',
            logo_a: 'https://kingsleague.pro/wp-content/uploads/2022/12/los-troncos.png',
            team_b: 'XBUYER TEAM',
            team_b_red: 'XBU',
            logo_b: 'https://kingsleague.pro/wp-content/uploads/2022/11/xbuyer-team.svg',
            goals_a: 5,
            goals_b: 3,
         },
         {
            team_a: 'Aniquiladores FC',
            team_a_red: 'ANI',
            logo_a: 'https://kingsleague.pro/wp-content/uploads/2022/11/aniquiladores.svg',
            team_b: 'Ultimate Móstoles',
            team_b_red: 'ULT',
            logo_b: 'https://kingsleague.pro/wp-content/uploads/2022/11/ultimate-mostoles.svg',
            goals_a: 1,
            goals_b: 5,
         },
         {
            team_a: 'Saiyans FC',
            team_a_red: 'SAI',
            logo_a: 'https://kingsleague.pro/wp-content/uploads/2022/11/saiyans-fc.svg',
            team_b: 'Porcinos FC',
            team_b_red: 'POR',
            logo_b: 'https://kingsleague.pro/wp-content/uploads/2022/11/porcinos-fc.svg',
            goals_a: 4,
            goals_b: 2,
         },
      ],
   },
   {
      week: 2,
      date: '08/01/2023',
      played: true,
      results: [
         {
            team_a: 'Jijantes FC',
            team_a_red: 'JFC',
            logo_a: 'https://kingsleague.pro/wp-content/uploads/2022/11/jijantes-fc.svg',
            team_b: 'Rayo de Barcelona',
            team_b_red: 'RDB',
            logo_b: 'https://kingsleague.pro/wp-content/uploads/2022/11/rayo-barcelona.svg',
            goals_a: 3,
            goals_b: 5,
         },
         {
            team_a: 'Ultimate Móstoles',
            team_a_red: 'ULT',
            logo_a: 'https://kingsleague.pro/wp-content/uploads/2022/11/ultimate-mostoles.svg',
            team_b: 'El Barrio',
            team_b_red: 'ELB',
            logo_b: 'https://kingsleague.pro/wp-content/uploads/2022/11/el-bbarrio.svg',
            goals_a: 3,
            goals_b: 2,
         },
         {
            team_a: '1K FC',
            team_a_red: '1K',
            logo_a: 'https://kingsleague.pro/wp-content/uploads/2022/11/1k.svg',
            team_b: 'Aniquiladores FC',
            team_b_red: 'ANI',
            logo_b: 'https://kingsleague.pro/wp-content/uploads/2022/11/aniquiladores.svg',
            goals_a: 3,
            goals_b: 2,
         },
         {
            team_a: 'Porcinos FC',
            team_a_red: 'POR',
            logo_a: 'https://kingsleague.pro/wp-content/uploads/2022/11/porcinos-fc.svg',
            team_b: 'Los Troncos FC',
            team_b_red: 'TFC',
            logo_b: 'https://kingsleague.pro/wp-content/uploads/2022/12/los-troncos.png',
            goals_a: 5,
            goals_b: 3,
         },
         {
            team_a: 'XBUYER TEAM',
            team_a_red: 'XBU',
            logo_a: 'https://kingsleague.pro/wp-content/uploads/2022/11/xbuyer-team.svg',
            team_b: 'Kunisports',
            team_b_red: 'KNS',
            logo_b: 'https://kingsleague.pro/wp-content/uploads/2022/11/kunisports.svg',
            goals_a: 0,
            goals_b: 1,
         },
         {
            team_a: 'PIO FC',
            team_a_red: 'PIO',
            logo_a: 'https://kingsleague.pro/wp-content/uploads/2022/11/pio.svg',
            team_b: 'Saiyans FC',
            team_b_red: 'SAI',
            logo_b: 'https://kingsleague.pro/wp-content/uploads/2022/11/saiyans-fc.svg',
            goals_a: 1,
            goals_b: 1,
            penalti_a: 2,
            penalti_b: 3,
         },
      ],
   },
   {
      week: 3,
      date: '15/01/2023',
      played: true,
      results: [
         {
            team_a: 'Jijantes FC',
            team_a_red: 'JFC',
            logo_a: 'https://kingsleague.pro/wp-content/uploads/2022/11/jijantes-fc.svg',
            team_b: '1K FC',
            team_b_red: '1K',
            logo_b: 'https://kingsleague.pro/wp-content/uploads/2022/11/1k.svg',
            goals_a: 3,
            goals_b: 5,
         },
         {
            team_a: 'Rayo de Barcelona',
            team_a_red: 'RDB',
            logo_a: 'https://kingsleague.pro/wp-content/uploads/2022/11/rayo-barcelona.svg',
            team_b: 'XBUYER TEAM',
            team_b_red: 'XBU',
            logo_b: 'https://kingsleague.pro/wp-content/uploads/2022/11/xbuyer-team.svg',
            goals_a: 2,
            goals_b: 2,
            penalti_a: 0,
            penalti_b: 3,
         },
         {
            team_a: 'Saiyans FC',
            team_a_red: 'SAI',
            logo_a: 'https://kingsleague.pro/wp-content/uploads/2022/11/saiyans-fc.svg',
            team_b: 'Ultimate Móstoles',
            team_b_red: 'ULT',
            logo_b: 'https://kingsleague.pro/wp-content/uploads/2022/11/ultimate-mostoles.svg',
            goals_a: 5,
            goals_b: 1,
         },
         {
            team_a: 'Kunisports',
            team_a_red: 'KNS',
            logo_a: 'https://kingsleague.pro/wp-content/uploads/2022/11/kunisports.svg',
            team_b: 'Porcinos FC',
            team_b_red: 'POR',
            logo_b: 'https://kingsleague.pro/wp-content/uploads/2022/11/porcinos-fc.svg',
            goals_a: 2,
            goals_b: 2,
            penalti_a: 2,
            penalti_b: 3,
         },
         {
            team_a: 'Los Troncos FC',
            team_a_red: 'TFC',
            logo_a: 'https://kingsleague.pro/wp-content/uploads/2022/12/los-troncos.png',
            team_b: 'PIO FC',
            team_b_red: 'PIO',
            logo_b: 'https://kingsleague.pro/wp-content/uploads/2022/11/pio.svg',
            goals_a: 3,
            goals_b: 2,
         },
         {
            team_a: 'El Barrio',
            team_a_red: 'ELB',
            logo_a: 'https://kingsleague.pro/wp-content/uploads/2022/11/el-bbarrio.svg',
            team_b: 'Aniquiladores FC',
            team_b_red: 'ANI',
            logo_b: 'https://kingsleague.pro/wp-content/uploads/2022/11/aniquiladores.svg',
            goals_a: 1,
            goals_b: 4,
         },
      ],
   },
   {
      week: 4,
      date: '22/01/2023',
      played: true,
      results: [
         {
            team_a: 'XBUYER TEAM',
            team_a_red: 'XBU',
            logo_a: 'https://kingsleague.pro/wp-content/uploads/2022/11/xbuyer-team.svg',
            team_b: 'Jijantes FC',
            team_b_red: 'JFC',
            logo_b: 'https://kingsleague.pro/wp-content/uploads/2022/11/jijantes-fc.svg',
            goals_a: 3,
            goals_b: 2,
         },
         {
            team_a: 'PIO FC',
            team_a_red: 'PIO',
            logo_a: 'https://kingsleague.pro/wp-content/uploads/2022/11/pio.svg',
            team_b: 'Kunisports',
            team_b_red: 'KNS',
            logo_b: 'https://kingsleague.pro/wp-content/uploads/2022/11/kunisports.svg',
            goals_a: 2,
            goals_b: 2,
            penalti_a: 1,
            penalti_b: 2,
         },
         {
            team_a: '1K FC',
            team_a_red: '1K',
            logo_a: 'https://kingsleague.pro/wp-content/uploads/2022/11/1k.svg',
            team_b: 'El Barrio',
            team_b_red: 'ELB',
            logo_b: 'https://kingsleague.pro/wp-content/uploads/2022/11/el-bbarrio.svg',
            goals_a: 2,
            goals_b: 5,
         },
         {
            team_a: 'Porcinos FC',
            team_a_red: 'POR',
            logo_a: 'https://kingsleague.pro/wp-content/uploads/2022/11/porcinos-fc.svg',
            team_b: 'Rayo de Barcelona',
            team_b_red: 'RDB',
            logo_b: 'https://kingsleague.pro/wp-content/uploads/2022/11/rayo-barcelona.svg',
            goals_a: 5,
            goals_b: 1,
         },
         {
            team_a: 'Aniquiladores FC',
            team_a_red: 'ANI',
            logo_a: 'https://kingsleague.pro/wp-content/uploads/2022/11/aniquiladores.svg',
            team_b: 'Saiyans FC',
            team_b_red: 'SAI',
            logo_b: 'https://kingsleague.pro/wp-content/uploads/2022/11/saiyans-fc.svg',
            goals_a: 1,
            goals_b: 1,
            penalti_a: 3,
            penalti_b: 2,
         },
         {
            team_a: 'Ultimate Móstoles',
            team_a_red: 'ULT',
            logo_a: 'https://kingsleague.pro/wp-content/uploads/2022/11/ultimate-mostoles.svg',
            team_b: 'Los Troncos FC',
            team_b_red: 'TFC',
            logo_b: 'https://kingsleague.pro/wp-content/uploads/2022/12/los-troncos.png',
            goals_a: 5,
            goals_b: 1,
         },
      ],
   },
   {
      week: 5,
      date: '05/02/2023',
      played: true,
      results: [
         {
            team_a: 'XBUYER TEAM',
            team_a_red: 'XBU',
            logo_a: 'https://kingsleague.pro/wp-content/uploads/2022/11/xbuyer-team.svg',
            team_b: '1K FC',
            team_b_red: '1K',
            logo_b: 'https://kingsleague.pro/wp-content/uploads/2022/11/1k.svg',
            goals_a: 3,
            goals_b: 2,
         },
         {
            team_a: 'Saiyans FC',
            team_a_red: 'SAI',
            logo_a: 'https://kingsleague.pro/wp-content/uploads/2022/11/saiyans-fc.svg',
            team_b: 'El Barrio',
            team_b_red: 'ELB',
            logo_b: 'https://kingsleague.pro/wp-content/uploads/2022/11/el-bbarrio.svg',
            goals_a: 1,
            goals_b: 0,
         },
         {
            team_a: 'Kunisports',
            team_a_red: 'KNS',
            logo_a: 'https://kingsleague.pro/wp-content/uploads/2022/11/kunisports.svg',
            team_b: 'Ultimate Móstoles',
            team_b_red: 'ULT',
            logo_b: 'https://kingsleague.pro/wp-content/uploads/2022/11/ultimate-mostoles.svg',
            goals_a: 3,
            goals_b: 1,
         },
         {
            team_a: 'Jijantes FC',
            team_a_red: 'JFC',
            logo_a: 'https://kingsleague.pro/wp-content/uploads/2022/11/jijantes-fc.svg',
            team_b: 'Porcinos FC',
            team_b_red: 'POR',
            logo_b: 'https://kingsleague.pro/wp-content/uploads/2022/11/porcinos-fc.svg',
            goals_a: 2,
            goals_b: 4,
         },
         {
            team_a: 'Rayo de Barcelona',
            team_a_red: 'RDB',
            logo_a: 'https://kingsleague.pro/wp-content/uploads/2022/11/rayo-barcelona.svg',
            team_b: 'PIO FC',
            team_b_red: 'PIO',
            logo_b: 'https://kingsleague.pro/wp-content/uploads/2022/11/pio.svg',
            goals_a: 5,
            goals_b: 4,
         },
         {
            team_a: 'Los Troncos FC',
            team_a_red: 'TFC',
            logo_a: 'https://kingsleague.pro/wp-content/uploads/2022/12/los-troncos.png',
            team_b: 'Aniquiladores FC',
            team_b_red: 'ANI',
            logo_b: 'https://kingsleague.pro/wp-content/uploads/2022/11/aniquiladores.svg',
            goals_a: 5,
            goals_b: 7,
         },
      ],
   },
   {
      week: 6,
      date: '12/02/2023',
      played: true,
      results: [
         {
            team_a: 'PIO FC',
            team_a_red: 'PIO',
            logo_a: 'https://kingsleague.pro/wp-content/uploads/2022/11/pio.svg',
            team_b: 'Jijantes FC',
            team_b_red: 'JFC',
            logo_b: 'https://kingsleague.pro/wp-content/uploads/2022/11/jijantes-fc.svg',
            goals_a: 5,
            goals_b: 0,
         },
         {
            team_a: 'El Barrio',
            team_a_red: 'ELB',
            logo_a: 'https://kingsleague.pro/wp-content/uploads/2022/11/el-bbarrio.svg',
            team_b: 'Los Troncos FC',
            team_b_red: 'TFC',
            logo_b: 'https://kingsleague.pro/wp-content/uploads/2022/12/los-troncos.png',
            goals_a: 3,
            goals_b: 3,
            penalti_a: 1,
            penalti_b: 4,
         },
         {
            team_a: 'Ultimate Móstoles',
            team_a_red: 'ULT',
            logo_a: 'https://kingsleague.pro/wp-content/uploads/2022/11/ultimate-mostoles.svg',
            team_b: 'Rayo de Barcelona',
            team_b_red: 'RDB',
            logo_b: 'https://kingsleague.pro/wp-content/uploads/2022/11/rayo-barcelona.svg',
            goals_a: 3,
            goals_b: 2,
         },
         {
            team_a: 'Aniquiladores FC',
            team_a_red: 'ANI',
            logo_a: 'https://kingsleague.pro/wp-content/uploads/2022/11/aniquiladores.svg',
            team_b: 'Kunisports',
            team_b_red: 'KNS',
            logo_b: 'https://kingsleague.pro/wp-content/uploads/2022/11/kunisports.svg',
            goals_a: 2,
            goals_b: 3,
         },
         {
            team_a: 'Porcinos FC',
            team_a_red: 'POR',
            logo_a: 'https://kingsleague.pro/wp-content/uploads/2022/11/porcinos-fc.svg',
            team_b: 'XBUYER TEAM',
            team_b_red: 'XBU',
            logo_b: 'https://kingsleague.pro/wp-content/uploads/2022/11/xbuyer-team.svg',
            goals_a: 4,
            goals_b: 3,
         },
         {
            team_a: '1K FC',
            team_a_red: '1K',
            logo_a: 'https://kingsleague.pro/wp-content/uploads/2022/11/1k.svg',
            team_b: 'Saiyans FC',
            team_b_red: 'SAI',
            logo_b: 'https://kingsleague.pro/wp-content/uploads/2022/11/saiyans-fc.svg',
            goals_a: 2,
            goals_b: 2,
            penalti_a: 3,
            penalti_b: 4,
         },
      ],
   },
   {
      week: 7,
      date: '19/02/2023',
      played: true,
      results: [
         {
            team_a: 'Rayo de Barcelona',
            team_a_red: 'RDB',
            logo_a: 'https://kingsleague.pro/wp-content/uploads/2022/11/rayo-barcelona.svg',
            team_b: 'Aniquiladores FC',
            team_b_red: 'ANI',
            logo_b: 'https://kingsleague.pro/wp-content/uploads/2022/11/aniquiladores.svg',
            goals_a: 3,
            goals_b: 2,
         },
         {
            team_a: 'Porcinos FC',
            team_a_red: 'POR',
            logo_a: 'https://kingsleague.pro/wp-content/uploads/2022/11/porcinos-fc.svg',
            team_b: '1K FC',
            team_b_red: '1K',
            logo_b: 'https://kingsleague.pro/wp-content/uploads/2022/11/1k.svg',
            goals_a: 5,
            goals_b: 2,
         },
         {
            team_a: 'Jijantes FC',
            team_a_red: 'JFC',
            logo_a: 'https://kingsleague.pro/wp-content/uploads/2022/11/jijantes-fc.svg',
            team_b: 'Ultimate Móstoles',
            team_b_red: 'ULT',
            logo_b: 'https://kingsleague.pro/wp-content/uploads/2022/11/ultimate-mostoles.svg',
            goals_a: 3,
            goals_b: 4,
         },
         {
            team_a: 'XBUYER TEAM',
            team_a_red: 'XBU',
            logo_a: 'https://kingsleague.pro/wp-content/uploads/2022/11/xbuyer-team.svg',
            team_b: 'PIO FC',
            team_b_red: 'PIO',
            logo_b: 'https://kingsleague.pro/wp-content/uploads/2022/11/pio.svg',
            goals_a: 2,
            goals_b: 5,
         },
         {
            team_a: 'Los Troncos FC',
            team_a_red: 'TFC',
            logo_a: 'https://kingsleague.pro/wp-content/uploads/2022/12/los-troncos.png',
            team_b: 'Saiyans FC',
            team_b_red: 'SAI',
            logo_b: 'https://kingsleague.pro/wp-content/uploads/2022/11/saiyans-fc.svg',
            goals_a: 0,
            goals_b: 1,
         },
         {
            team_a: 'Kunisports',
            team_a_red: 'KNS',
            logo_a: 'https://kingsleague.pro/wp-content/uploads/2022/11/kunisports.svg',
            team_b: 'El Barrio',
            team_b_red: 'ELB',
            logo_b: 'https://kingsleague.pro/wp-content/uploads/2022/11/el-bbarrio.svg',
            goals_a: 2,
            goals_b: 6,
         },
      ],
   },
   {
      week: 8,
      date: '26/02/2023',
      played: true,
      results: [
         {
            team_a: 'Aniquiladores FC',
            team_a_red: 'ANI',
            logo_a: 'https://kingsleague.pro/wp-content/uploads/2022/11/aniquiladores.svg',
            team_b: 'Jijantes FC',
            team_b_red: 'JFC',
            logo_b: 'https://kingsleague.pro/wp-content/uploads/2022/11/jijantes-fc.svg',
            goals_a: 4,
            goals_b: 2,
         },
         {
            team_a: 'El Barrio',
            team_a_red: 'ELB',
            logo_a: 'https://kingsleague.pro/wp-content/uploads/2022/11/el-bbarrio.svg',
            team_b: 'Rayo de Barcelona',
            team_b_red: 'RDB',
            logo_b: 'https://kingsleague.pro/wp-content/uploads/2022/11/rayo-barcelona.svg',
            goals_a: 4,
            goals_b: 2,
         },
         {
            team_a: 'Ultimate Móstoles',
            team_a_red: 'ULT',
            logo_a: 'https://kingsleague.pro/wp-content/uploads/2022/11/ultimate-mostoles.svg',
            team_b: 'XBUYER TEAM',
            team_b_red: 'XBU',
            logo_b: 'https://kingsleague.pro/wp-content/uploads/2022/11/xbuyer-team.svg',
            goals_a: 2,
            goals_b: 1,
         },
         {
            team_a: 'Saiyans FC',
            team_a_red: 'SAI',
            logo_a: 'https://kingsleague.pro/wp-content/uploads/2022/11/saiyans-fc.svg',
            team_b: 'Kunisports',
            team_b_red: 'KNS',
            logo_b: 'https://kingsleague.pro/wp-content/uploads/2022/11/kunisports.svg',
            goals_a: 1,
            goals_b: 3,
         },
         {
            team_a: '1K FC',
            team_a_red: '1K',
            logo_a: 'https://kingsleague.pro/wp-content/uploads/2022/11/1k.svg',
            team_b: 'Los Troncos FC',
            team_b_red: 'TFC',
            logo_b: 'https://kingsleague.pro/wp-content/uploads/2022/12/los-troncos.png',
            goals_a: 4,
            goals_b: 5,
         },
         {
            team_a: 'PIO FC',
            team_a_red: 'PIO',
            logo_a: 'https://kingsleague.pro/wp-content/uploads/2022/11/pio.svg',
            team_b: 'Porcinos FC',
            team_b_red: 'POR',
            logo_b: 'https://kingsleague.pro/wp-content/uploads/2022/11/porcinos-fc.svg',
            goals_a: 0,
            goals_b: 0,
            penalti_a: 3,
            penalti_b: 1,
         },
      ],
   },
   {
      week: 9,
      date: '05/03/2023',
      played: false,
      results: [
         {
            team_a: 'Rayo de Barcelona',
            team_a_red: 'RDB',
            logo_a: 'https://kingsleague.pro/wp-content/uploads/2022/11/rayo-barcelona.svg',
            team_b: 'Saiyans FC',
            team_b_red: 'SAI',
            logo_b: 'https://kingsleague.pro/wp-content/uploads/2022/11/saiyans-fc.svg',
            time: '16:00',
         },
         {
            team_a: 'PIO FC',
            team_a_red: 'PIO',
            logo_a: 'https://kingsleague.pro/wp-content/uploads/2022/11/pio.svg',
            team_b: '1K FC',
            team_b_red: '1K',
            logo_b: 'https://kingsleague.pro/wp-content/uploads/2022/11/1k.svg',
            time: '17:00',
         },
         {
            team_a: 'Porcinos FC',
            team_a_red: 'POR',
            logo_a: 'https://kingsleague.pro/wp-content/uploads/2022/11/porcinos-fc.svg',
            team_b: 'Ultimate Móstoles',
            team_b_red: 'ULT',
            logo_b: 'https://kingsleague.pro/wp-content/uploads/2022/11/ultimate-mostoles.svg',
            time: '18:00',
         },
         {
            team_a: 'Kunisports',
            team_a_red: 'KNS',
            logo_a: 'https://kingsleague.pro/wp-content/uploads/2022/11/kunisports.svg',
            team_b: 'Los Troncos FC',
            team_b_red: 'TFC',
            logo_b: 'https://kingsleague.pro/wp-content/uploads/2022/12/los-troncos.png',
            time: '19:00',
         },
         {
            team_a: 'Jijantes FC',
            team_a_red: 'JFC',
            logo_a: 'https://kingsleague.pro/wp-content/uploads/2022/11/jijantes-fc.svg',
            team_b: 'El Barrio',
            team_b_red: 'ELB',
            logo_b: 'https://kingsleague.pro/wp-content/uploads/2022/11/el-bbarrio.svg',
            time: '20:00',
         },
         {
            team_a: 'XBUYER TEAM',
            team_a_red: 'XBU',
            logo_a: 'https://kingsleague.pro/wp-content/uploads/2022/11/xbuyer-team.svg',
            team_b: 'Aniquiladores FC',
            team_b_red: 'ANI',
            logo_b: 'https://kingsleague.pro/wp-content/uploads/2022/11/aniquiladores.svg',
            time: '21:00',
         },
      ],
   },
   {
      week: 10,
      date: '12/03/2023',
      played: false,
      results: [
         {
            team_a: 'Aniquiladores FC',
            team_a_red: 'ANI',
            logo_a: 'https://kingsleague.pro/wp-content/uploads/2022/11/aniquiladores.svg',
            team_b: 'Porcinos FC',
            team_b_red: 'POR',
            logo_b: 'https://kingsleague.pro/wp-content/uploads/2022/11/porcinos-fc.svg',
            time: '',
         },
         {
            team_a: 'El Barrio',
            team_a_red: 'ELB',
            logo_a: 'https://kingsleague.pro/wp-content/uploads/2022/11/el-bbarrio.svg',
            team_b: 'XBUYER TEAM',
            team_b_red: 'XBU',
            logo_b: 'https://kingsleague.pro/wp-content/uploads/2022/11/xbuyer-team.svg',
            time: '',
         },
         {
            team_a: 'Kunisports',
            team_a_red: 'KNS',
            logo_a: 'https://kingsleague.pro/wp-content/uploads/2022/11/kunisports.svg',
            team_b: '1K FC',
            team_b_red: '1K',
            logo_b: 'https://kingsleague.pro/wp-content/uploads/2022/11/1k.svg',
            time: '',
         },
         {
            team_a: 'Saiyans FC',
            team_a_red: 'SAI',
            logo_a: 'https://kingsleague.pro/wp-content/uploads/2022/11/saiyans-fc.svg',
            team_b: 'Jijantes FC',
            team_b_red: 'JFC',
            logo_b: 'https://kingsleague.pro/wp-content/uploads/2022/11/jijantes-fc.svg',
            time: '',
         },
         {
            team_a: 'Ultimate Móstoles',
            team_a_red: 'ULT',
            logo_a: 'https://kingsleague.pro/wp-content/uploads/2022/11/ultimate-mostoles.svg',
            team_b: 'PIO FC',
            team_b_red: 'PIO',
            logo_b: 'https://kingsleague.pro/wp-content/uploads/2022/11/pio.svg',
            time: '',
         },
         {
            team_a: 'Los Troncos FC',
            team_a_red: 'TFC',
            logo_a: 'https://kingsleague.pro/wp-content/uploads/2022/12/los-troncos.png',
            team_b: 'Rayo de Barcelona',
            team_b_red: 'RDB',
            logo_b: 'https://kingsleague.pro/wp-content/uploads/2022/11/rayo-barcelona.svg',
            time: '',
         },
      ],
   },
   {
      week: 11,
      date: '19/03/2023',
      played: false,
      results: [
         {
            team_a: '1K FC',
            team_a_red: '1K',
            logo_a: 'https://kingsleague.pro/wp-content/uploads/2022/11/1k.svg',
            team_b: 'Ultimate Móstoles',
            team_b_red: 'ULT',
            logo_b: 'https://kingsleague.pro/wp-content/uploads/2022/11/ultimate-mostoles.svg',
            time: '',
         },
         {
            team_a: 'XBUYER TEAM',
            team_a_red: 'XBU',
            logo_a: 'https://kingsleague.pro/wp-content/uploads/2022/11/xbuyer-team.svg',
            team_b: 'Saiyans FC',
            team_b_red: 'SAI',
            logo_b: 'https://kingsleague.pro/wp-content/uploads/2022/11/saiyans-fc.svg',
            time: '',
         },
         {
            team_a: 'Porcinos FC',
            team_a_red: 'POR',
            logo_a: 'https://kingsleague.pro/wp-content/uploads/2022/11/porcinos-fc.svg',
            team_b: 'El Barrio',
            team_b_red: 'ELB',
            logo_b: 'https://kingsleague.pro/wp-content/uploads/2022/11/el-bbarrio.svg',
            time: '',
         },
         {
            team_a: 'PIO FC',
            team_a_red: 'PIO',
            logo_a: 'https://kingsleague.pro/wp-content/uploads/2022/11/pio.svg',
            team_b: 'Aniquiladores FC',
            team_b_red: 'ANI',
            logo_b: 'https://kingsleague.pro/wp-content/uploads/2022/11/aniquiladores.svg',
            time: '',
         },
         {
            team_a: 'Rayo de Barcelona',
            team_a_red: 'RDB',
            logo_a: 'https://kingsleague.pro/wp-content/uploads/2022/11/rayo-barcelona.svg',
            team_b: 'Kunisports',
            team_b_red: 'KNS',
            logo_b: 'https://kingsleague.pro/wp-content/uploads/2022/11/kunisports.svg',
            time: '',
         },
         {
            team_a: 'Jijantes FC',
            team_a_red: 'JFC',
            logo_a: 'https://kingsleague.pro/wp-content/uploads/2022/11/jijantes-fc.svg',
            team_b: 'Los Troncos FC',
            team_b_red: 'TFC',
            logo_b: 'https://kingsleague.pro/wp-content/uploads/2022/12/los-troncos.png',
            time: '',
         },
      ],
   },
];
