import { TeamsData } from '../types';

export const teams: Array<TeamsData> = [
   {
      name: 'Porcinos FC',
      logo: 'https://kingsleague.pro/wp-content/uploads/2022/11/porcinos-fc.svg',
      background: 'https://kingsleague.pro/wp-content/uploads/2022/12/porcinos-bg.jpg',
      logo_svg: 'https://kingsleague.pro/wp-content/uploads/2022/12/porcinos-inverse.svg',
      win: 6,
      loss: 3,
      goals: 31,
      received_goals: 22,
      assists: 4,
      yellow_cards: 1,
      red_cards: 0,
      president: {
         image: 'https://kingsleague.pro/wp-content/uploads/2022/12/IBAI-LLANOS-PORCINOS-FC.png',
         name: 'Ibai Llanos',
      },
      trainer: {
         image: 'https://kingsleague.pro/wp-content/uploads/porcinos/entrenador.png',
         name: 'Juvenal Edjogo-Owono',
      },
      players: [
         {
            image: 'https://kingsleague.pro/wp-content/uploads/porcinos/8.png',
            name: 'Espinosa',
            role: 'Jugador 11',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/porcinos/13.png',
            name: 'J. Segovia',
            role: 'Portero',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/porcinos/6.png',
            name: 'G. Cichero',
            role: 'Defensa',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/porcinos/23.png',
            name: 'David L.L.',
            role: 'Defensa',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/porcinos/21.png',
            name: 'Toti',
            role: 'Medio',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/2023/02/Porcinos_20.png',
            name: 'Carlitos G.',
            role: 'Medio',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/porcinos/9.png',
            name: 'Killian',
            role: 'Delantero',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/porcinos/7.png',
            name: 'J. Blanco',
            role: 'Delantero',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/2023/01/Porcinos_17.png',
            name: 'Uri Pons',
            role: 'Delantero',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/porcinos/4.png',
            name: 'Lao',
            role: 'Medio',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/porcinos/1.png',
            name: 'Sergi',
            role: 'Portero',
         },
      ],
      key: "porcinos-fc",
   },
   {
      name: 'Kunisports',
      logo: 'https://kingsleague.pro/wp-content/uploads/2022/11/kunisports.svg',
      background: 'https://kingsleague.pro/wp-content/uploads/2022/12/kunisports-bg.jpg',
      logo_svg: 'https://kingsleague.pro/wp-content/uploads/2022/12/kunisports-inverse.svg',
      win: 6,
      loss: 3,
      goals: 18,
      received_goals: 19,
      assists: 3,
      yellow_cards: 2,
      red_cards: 0,
      president: {
         name: 'Kun Agüero',
         image: 'https://kingsleague.pro/wp-content/uploads/2022/12/KUNSPORTS-KUN-AGUERO.png',
      },
      trainer: {
         name: 'Martín Posse',
         image: 'https://kingsleague.pro/wp-content/uploads/kunisports/entrenador.png',
      },
      players: [
         {
            image: 'https://kingsleague.pro/wp-content/uploads/2023/01/Kunisports_23.png',
            name: 'Coro',
            role: 'Jugador 11',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/kunisports/11.png',
            name: 'Torrentbó',
            role: 'Delantero',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/kunisports/1.png',
            name: 'Víctor',
            role: 'Portero',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/kunisports/4.png',
            name: 'Guerrero',
            role: 'Defensa',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/kunisports/8.png',
            name: 'Joan Inés',
            role: 'Medio',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/kunisports/13.png',
            name: 'Rode',
            role: 'Portero',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/kunisports/5.png',
            name: 'Ruggeri',
            role: 'Defensa',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/kunisports/6.png',
            name: 'Nacho J.',
            role: 'Defensa',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/kunisports/9.png',
            name: 'Hidalgo',
            role: 'Delantero',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/kunisports/7.png',
            name: 'Lluc',
            role: 'Delantero',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/kunisports/3.png',
            name: 'Miki',
            role: 'Defensa',
         },
      ],
      key: "kunisports",
   },
   {
      name: 'Ultimate Móstoles',
      logo: 'https://kingsleague.pro/wp-content/uploads/2022/11/ultimate-mostoles.svg',
      background: 'https://kingsleague.pro/wp-content/uploads/2022/12/mostoles-bg.jpg',
      logo_svg: 'https://kingsleague.pro/wp-content/uploads/2022/12/mostoles-inverse.svg',
      win: 7,
      loss: 2,
      goals: 29,
      received_goals: 22,
      assists: 5,
      yellow_cards: 1,
      red_cards: 0,
      president: {
         image: 'https://kingsleague.pro/wp-content/uploads/2022/12/DJMARIIO-ULTIMATE-MOSTOLES.png',
         name: 'DjMaRiiO',
      },
      trainer: {
         image: 'https://kingsleague.pro/wp-content/uploads/ultimate-mostoles/entrenador.png',
         name: 'Nacho Castro',
      },
      players: [
         {
            image: 'https://kingsleague.pro/wp-content/uploads/ultimate-mostoles/22.png',
            name: 'Juanma Glez.',
            role: 'Jugador 11',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/ultimate-mostoles/10.png',
            name: 'Arché',
            role: 'Medio',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/ultimate-mostoles/1.png',
            name: 'Iu',
            role: 'Portero',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/ultimate-mostoles/11.png',
            name: 'Guti',
            role: 'Defensa',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/ultimate-mostoles/6.png',
            name: 'Aleix',
            role: 'Medio',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/ultimate-mostoles/19.png',
            name: 'Llur',
            role: 'Delantero',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/ultimate-mostoles/4.png',
            name: 'Iker',
            role: 'Defensa',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/ultimate-mostoles/3.png',
            name: 'Ian',
            role: 'Defensa',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/ultimate-mostoles/7.png',
            name: 'Zea',
            role: 'Delantero',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/ultimate-mostoles/13.png',
            name: 'Nacho',
            role: 'Portero',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/ultimate-mostoles/20.png',
            name: 'Lucca',
            role: 'Medio',
         },
      ],
      key: "ultimate-mostoles",
   },
   {
      name: 'Rayo de Barcelona',
      logo: 'https://kingsleague.pro/wp-content/uploads/2022/11/rayo-barcelona.svg',
      background: 'https://kingsleague.pro/wp-content/uploads/2022/12/rayo-bg.jpg',
      logo_svg: 'https://kingsleague.pro/wp-content/uploads/2022/12/rayo-inverse.svg',
      win: 3,
      loss: 6,
      goals: 23,
      received_goals: 30,
      assists: 5,
      yellow_cards: 0,
      red_cards: 0,
      president: {
         image: 'https://kingsleague.pro/wp-content/uploads/2022/12/SPURSITO-RAYO-BARCELONA.png',
         name: 'Spursito',
      },
      trainer: {
         image: 'https://kingsleague.pro/wp-content/uploads/rayo-bcn/entrenador.png',
         name: 'JuanluDBZ',
      },
      players: [
         {
            image: 'https://kingsleague.pro/wp-content/uploads/rayo-bcn/45.png',
            name: 'Poloteli',
            role: 'Jugador 11',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/rayo-bcn/10.png',
            name: 'Pelaz',
            role: 'Medio',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/rayo-bcn/41.png',
            name: 'Canet',
            role: 'Portero',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/rayo-bcn/19.png',
            name: 'Guillem ZZ',
            role: 'Delantero',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/rayo-bcn/22.png',
            name: 'M. Reyes',
            role: 'Defensa',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/rayo-bcn/30.png',
            name: 'Franky P.',
            role: 'Medio',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/rayo-bcn/8.png',
            name: 'Dani P.',
            role: 'Medio',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/rayo-bcn/11.png',
            name: 'Alejandro',
            role: 'Defensa',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/rayo-bcn/9.png',
            name: 'Biboum M.',
            role: 'Delantero',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/rayo-bcn/63.png',
            name: 'Jonathan',
            role: 'Medio',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/rayo-bcn/77.png',
            name: 'Alex Race',
            role: 'Delantero',
         },
      ],
      key: "rayo-barcelona",
   },
   {
      name: 'Los Troncos FC',
      logo: 'https://kingsleague.pro/wp-content/uploads/2022/12/los-troncos.png',
      background: 'https://kingsleague.pro/wp-content/uploads/2022/12/troncos-bg.jpg',
      logo_svg: 'https://kingsleague.pro/wp-content/uploads/2022/12/troncos-inverse.svg',
      win: 5,
      loss: 4,
      goals: 29,
      received_goals: 30,
      assists: 7,
      yellow_cards: 2,
      red_cards: 0,
      president: {
         image: 'https://kingsleague.pro/wp-content/uploads/2022/12/PERXITAA-LOS-TRONCOS-FC.png',
         name: 'Perxitaa',
      },
      trainer: {
         image: 'https://kingsleague.pro/wp-content/uploads/troncos/entrenador.png',
         name: 'Pol Font',
      },
      players: [
         {
            image: 'https://kingsleague.pro/wp-content/uploads/troncos/21.png',
            name: 'C. Planas',
            role: 'Jugador 11',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/troncos/9.png',
            name: 'E. Álvaro',
            role: 'Delantero',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/troncos/13.png',
            name: 'P. Lechuga',
            role: 'Portero',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/troncos/4.png',
            name: 'D. Soriano',
            role: 'Defensa',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/troncos/8.png',
            name: 'S. Sánchez',
            role: 'Medio',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/troncos/5.png',
            name: 'Noel',
            role: 'Medio',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/troncos/10.png',
            name: 'X. Molas',
            role: 'Medio',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/troncos/7.png',
            name: 'R. Martínez',
            role: 'Delantero',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/troncos/11.png',
            name: 'Dorkis',
            role: 'Delantero',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/troncos/6.png',
            name: 'I. Nuevo',
            role: 'Medio',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/troncos/1.png',
            name: 'M. Arús',
            role: 'Portero',
         },
      ],
      key: "los-troncos-fc",
   },
   {
      name: 'PIO FC',
      logo: 'https://kingsleague.pro/wp-content/uploads/2022/11/pio.svg',
      background: 'https://kingsleague.pro/wp-content/uploads/2022/12/pio-bg.jpg',
      logo_svg: 'https://kingsleague.pro/wp-content/uploads/2022/12/pio-inverse.svg',
      win: 3,
      loss: 6,
      goals: 22,
      received_goals: 22,
      assists: 2,
      yellow_cards: 4,
      red_cards: 0,
      president: {
         image: 'https://kingsleague.pro/wp-content/uploads/2022/12/RIVERS-PIO-FC.png',
         name: 'Rivers',
      },
      trainer: {
         image: 'https://kingsleague.pro/wp-content/uploads/pio/entrenador.png',
         name: 'Gerardo Torrado',
      },
      players: [
         {
            image: 'https://kingsleague.pro/wp-content/uploads/pio/4.png',
            name: 'Lopo',
            role: 'Jugador 11',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/pio/1.png',
            name: 'Jorge',
            role: 'Portero',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/pio/2.png',
            name: 'Carlitos',
            role: 'Defensa',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/pio/6.png',
            name: 'Pau Fer',
            role: 'Medio',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/2023/01/Pio_9.png',
            name: 'I. Cabello',
            role: 'Delantero',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/pio/21.png',
            name: 'B. Juárez',
            role: 'Medio',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/pio/42.png',
            name: 'Turner',
            role: 'Defensa',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/pio/11.png',
            name: 'Adri',
            role: 'Delantero',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/pio/8.png',
            name: 'Cokita',
            role: 'Medio',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/pio/22.png',
            name: 'A. Ropero',
            role: 'Medio',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/pio/14.png',
            name: 'Santiago',
            role: 'Defensa',
         },
      ],
      key: "pio-fc",
   },
   {
      name: 'El Barrio',
      logo: 'https://kingsleague.pro/wp-content/uploads/2022/11/el-bbarrio.svg',
      background: 'https://kingsleague.pro/wp-content/uploads/2022/12/barrio-bg.jpg',
      logo_svg: 'https://kingsleague.pro/wp-content/uploads/2022/12/barrio-inverse.svg',
      win: 5,
      loss: 4,
      goals: 29,
      received_goals: 18,
      assists: 6,
      yellow_cards: 1,
      red_cards: 0,
      president: {
         image: 'https://kingsleague.pro/wp-content/uploads/2022/12/EL-BARRIO-ADRI-CONTRERAS.png',
         name: 'Adri Contreras',
      },
      trainer: {
         image: 'https://kingsleague.pro/wp-content/uploads/barrio/entrenador.png',
         name: 'Juan Arroita',
      },
      players: [
         {
            image: 'https://kingsleague.pro/wp-content/uploads/barrio/1.png',
            name: 'José Juan',
            role: 'Jugador 11',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/barrio/10.png',
            name: 'Jacobo',
            role: 'Delantero',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/barrio/6.png',
            name: 'Mase',
            role: 'Defensa',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/barrio/9.png',
            name: 'Beguer',
            role: 'Delantero',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/barrio/14.png',
            name: 'Ros',
            role: 'Medio',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/barrio/8.png',
            name: 'Ubón',
            role: 'Medio',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/barrio/19.png',
            name: 'Pau ZZ',
            role: 'Defensa',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/barrio/23.png',
            name: 'Olae',
            role: 'Delantero',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/barrio/11.png',
            name: 'O. Boada',
            role: 'Delantero',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/barrio/7.png',
            name: 'Baranera',
            role: 'Medio',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/barrio/12.png',
            name: 'Capilla',
            role: 'Medio',
         },
      ],
      key: "el-barrio",
   },
   {
      name: 'Aniquiladores FC',
      logo: 'https://kingsleague.pro/wp-content/uploads/2022/11/aniquiladores.svg',
      background: 'https://kingsleague.pro/wp-content/uploads/2022/12/aniquiladores-bg.jpg',
      logo_svg:
         'https://kingsleague.pro/wp-content/uploads/2022/12/aniquiladores-inverse.svg',
      win: 4,
      loss: 5,
      goals: 23,
      received_goals: 27,
      assists: 1,
      yellow_cards: 1,
      red_cards: 0,
      president: {
         image: 'https://kingsleague.pro/wp-content/uploads/2022/12/JUAN-GUARNIZO-ANIQUILADORES-FC.png',
         name: 'Juan Guarnizo',
      },
      trainer: {
         image: 'https://kingsleague.pro/wp-content/uploads/aniquiladores/entrenador.png',
         name: 'Sergio Verdirame',
      },
      players: [
         {
            image: 'https://kingsleague.pro/wp-content/uploads/aniquiladores/14.png',
            name: 'F. Hernández',
            role: 'Jugador 11',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/aniquiladores/25.png',
            name: 'Daniel P.',
            role: 'Portero',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/aniquiladores/8.png',
            name: 'Galvany',
            role: 'Medio',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/aniquiladores/5.png',
            name: 'Andrés',
            role: 'Defensa',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/aniquiladores/31.png',
            name: 'Bernat',
            role: 'Medio',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/aniquiladores/24.png',
            name: 'Paul Mañé',
            role: 'Delantero',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/aniquiladores/22.png',
            name: 'Jorquera',
            role: 'Defensa',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/aniquiladores/9.png',
            name: 'Gilles V.',
            role: 'Medio',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/aniquiladores/21.png',
            name: 'Jadir',
            role: 'Defensa',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/aniquiladores/11.png',
            name: 'Roger',
            role: 'Medio',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/aniquiladores/10.png',
            name: 'X.Morales',
            role: 'Portero',
         },
      ],
      key: "aniquiladores-fc",
   },
   {
      name: 'XBUYER TEAM',
      logo: 'https://kingsleague.pro/wp-content/uploads/2022/11/xbuyer-team.svg',
      background: 'https://kingsleague.pro/wp-content/uploads/2022/12/xb-bg.jpg',
      logo_svg: 'https://kingsleague.pro/wp-content/uploads/2022/12/xb-inverse.svg',
      win: 4,
      loss: 5,
      goals: 21,
      received_goals: 23,
      assists: 1,
      yellow_cards: 3,
      red_cards: 0,
      president: {
         image: 'https://kingsleague.pro/wp-content/uploads/2022/12/BUYER-TEAM-xbuyer.png',
         name: 'Hnos. Buyer',
      },
      trainer: {
         image: 'https://kingsleague.pro/wp-content/uploads/xbuyer/entrenador.png',
         name: 'Victor González',
      },
      players: [
         {
            image: 'https://kingsleague.pro/wp-content/uploads/xbuyer/10.png',
            name: 'C. Castro',
            role: 'Jugador 11',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/xbuyer/13.png',
            name: 'Capi',
            role: 'Portero',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/xbuyer/9.png',
            name: 'Poch',
            role: 'Delantero',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/xbuyer/20.png',
            name: 'Iñaki',
            role: 'Medio',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/xbuyer/5.png',
            name: 'Dani',
            role: 'Defensa',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/xbuyer/32.png',
            name: 'Granero',
            role: 'Delantero',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/xbuyer/11.png',
            name: 'Goran',
            role: 'Medio',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/xbuyer/3.png',
            name: 'Bañuls',
            role: 'Defensa',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/xbuyer/7.png',
            name: 'Franc',
            role: 'Medio',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/xbuyer/21.png',
            name: 'B. Sierra',
            role: 'Delantero',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/xbuyer/1.png',
            name: 'Sep',
            role: 'Portero',
         },
      ],
      key: "xbuyer-team",
   },
   {
      name: 'Saiyans FC',
      logo: 'https://kingsleague.pro/wp-content/uploads/2022/11/saiyans-fc.svg',
      background: 'https://kingsleague.pro/wp-content/uploads/2022/12/saiyans-bg.jpg',
      logo_svg: 'https://kingsleague.pro/wp-content/uploads/2022/12/saiyans-inverse.svg',
      win: 7,
      loss: 2,
      goals: 19,
      received_goals: 11,
      assists: 8,
      yellow_cards: 3,
      red_cards: 1,
      president: {
         image: 'https://kingsleague.pro/wp-content/uploads/2022/12/THEGREFG-SAIYANS-FC.png',
         name: 'TheGrefg',
      },
      trainer: {
         image: 'https://kingsleague.pro/wp-content/uploads/saiyans/entrenador.png',
         name: 'Daniel Romo',
      },
      players: [
         {
            image: 'https://kingsleague.pro/wp-content/uploads/2023/01/Saiyans_8.png',
            name: 'Pol Alme',
            role: 'Jugador 11',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/saiyans/1.png',
            name: 'Briones',
            role: 'Portero',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/saiyans/9.png',
            name: 'Gio Ferinu',
            role: 'Delantero',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/saiyans/4.png',
            name: 'Campu',
            role: 'Defensa',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/saiyans/7.png',
            name: 'Temo',
            role: 'Medio',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/saiyans/14.png',
            name: 'C. Valle',
            role: 'Medio',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/saiyans/5.png',
            name: 'V. Torres',
            role: 'Defensa',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/saiyans/20.png',
            name: 'Feliu',
            role: 'Medio',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/saiyans/10.png',
            name: 'David Alba',
            role: 'Delantero',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/saiyans/11.png',
            name: 'R. Carbó',
            role: 'Medio',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/saiyans/22.png',
            name: 'Fajardo',
            role: 'Portero',
         },
      ],
      key: "saiyans-fc",
   },
   {
      name: 'Jijantes FC',
      logo: 'https://kingsleague.pro/wp-content/uploads/2022/11/jijantes-fc.svg',
      background: 'https://kingsleague.pro/wp-content/uploads/2022/12/jijantes-bg.jpg',
      logo_svg: 'https://kingsleague.pro/wp-content/uploads/2022/12/jijantes-inverse.svg',
      win: 0,
      loss: 9,
      goals: 17,
      received_goals: 35,
      assists: 4,
      yellow_cards: 2,
      red_cards: 0,
      president: {
         image: 'https://kingsleague.pro/wp-content/uploads/2022/12/Gerard-Romero.png',
         name: 'Gerard Romero',
      },
      trainer: {
         image: 'https://kingsleague.pro/wp-content/uploads/jijantes/entrenador.png',
         name: 'Marc Carmona',
      },
      players: [
         {
            image: 'https://kingsleague.pro/wp-content/uploads/jijantes/26.png',
            name: 'Soriano',
            role: 'Jugador 11',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/jijantes/8.png',
            name: 'Alsina',
            role: 'Medio',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/jijantes/1.png',
            name: 'Pol',
            role: 'Portero',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/jijantes/4.png',
            name: 'Jay',
            role: 'Defensa',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/jijantes/7.png',
            name: 'Quero',
            role: 'Medio',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/jijantes/5.png',
            name: 'Arnau M.V',
            role: 'Defensa',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/2023/02/Jijantes_9.png',
            name: 'Iván',
            role: 'Delantero',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/jijantes/30.png',
            name: 'Maca',
            role: 'Medio',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/jijantes/6.png',
            name: 'Noel',
            role: 'Defensa',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/jijantes/31.png',
            name: 'Dorado',
            role: 'Delantero',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/jijantes/25.png',
            name: 'Mario',
            role: 'Portero',
         },
      ],
      key: "jijantes-fc",
   },
   {
      name: '1K FC',
      logo: 'https://kingsleague.pro/wp-content/uploads/2022/11/1k.svg',
      background: 'https://kingsleague.pro/wp-content/uploads/2022/12/1k-bg.jpg',
      logo_svg: 'https://kingsleague.pro/wp-content/uploads/2022/12/1k-inverse.svg',
      win: 4,
      loss: 5,
      goals: 28,
      received_goals: 30,
      assists: 6,
      yellow_cards: 0,
      red_cards: 0,
      president: {
         image: 'https://kingsleague.pro/wp-content/uploads/2022/12/1K-IKER-CASILLAS.png',
         name: 'Iker Casillas',
      },
      trainer: {
         image: 'https://kingsleague.pro/wp-content/uploads/1k/entrenador.png',
         name: 'Julio García Mera',
      },
      players: [
         {
            image: 'https://kingsleague.pro/wp-content/uploads/1k/1.png',
            name: 'Ricardo',
            role: 'Jugador 11',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/1k/0.png',
            name: 'Román',
            role: 'Defensa',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/1k/7.png',
            name: 'Sorroche',
            role: 'Delantero',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/1k/97.png',
            name: 'Marino',
            role: 'Delantero',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/1k/3.png',
            name: 'Ledo',
            role: 'Defensa',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/1k/8.png',
            name: 'Sauras',
            role: 'Defensa',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/1k/14.png',
            name: 'Bruno',
            role: 'Defensa',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/1k/80.png',
            name: 'Pluvins',
            role: 'Medio',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/1k/10.png',
            name: 'Rivero',
            role: 'Medio',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/1k/9.png',
            name: 'Lautaro',
            role: 'Delantero',
         },
         {
            image: 'https://kingsleague.pro/wp-content/uploads/1k/11.png',
            name: 'Günter',
            role: 'Delantero',
         },
      ],
      key: "1k-fc",
   },
];
